; ================================================================================
; Sprite Mappings - generated by Flex 2 Sat Sep 01 2018 07:42:12 GMT-0700 (Pacific Daylight Time)
; ================================================================================

DATA4ZWA3RPDLRR:
	dc.w DATA4ZWA3RPDLRR_0-DATA4ZWA3RPDLRR, DATA4ZWA3RPDLRR_1-DATA4ZWA3RPDLRR
	dc.w DATA4ZWA3RPDLRR_2-DATA4ZWA3RPDLRR
DATA4ZWA3RPDLRR_0: dc.b $2
	dc.b $F8, $9, $0, $4, $E8
	dc.b $F8, $9, $8, $4, $0
DATA4ZWA3RPDLRR_1: dc.b $1
	dc.b $F8, $5, $0, $0, $F8
DATA4ZWA3RPDLRR_2: dc.b $1
	dc.b $F8, $5, $0, $A, $F8
	even