; ================================================================================
; Sprite Mappings - generated by Flex 2 Sat Jul 28 2018 22:10:15 GMT-0700 (Pacific Daylight Time)
; ================================================================================

DATA55FC54GRGPG:
	dc.w DATA55FC54GRGPG_0-DATA55FC54GRGPG, DATA55FC54GRGPG_1-DATA55FC54GRGPG
	dc.w DATA55FC54GRGPG_2-DATA55FC54GRGPG, DATA55FC54GRGPG_3-DATA55FC54GRGPG
	dc.w DATA55FC54GRGPG_4-DATA55FC54GRGPG, DATA55FC54GRGPG_5-DATA55FC54GRGPG
DATA55FC54GRGPG_0: dc.b $1
	dc.b $E8, $7, $0, $0, $F8
DATA55FC54GRGPG_1: dc.b $1
	dc.b $E8, $7, $0, $8, $F8
DATA55FC54GRGPG_2: dc.b $1
	dc.b $F0, $6, $0, $10, $F8
DATA55FC54GRGPG_3: dc.b $1
	dc.b $F8, $D, $0, $16, $E8
DATA55FC54GRGPG_4: dc.b $1
	dc.b $F8, $D, $0, $1E, $E8
DATA55FC54GRGPG_5: dc.b $1
	dc.b $F8, $9, $0, $26, $F0
	even