; ================================================================================
; Sprite Mappings - generated by Flex 2 Sun Oct 21 2018 10:24:17 GMT-0700 (Pacific Daylight Time)
; ================================================================================

DATAG2L5RZ4HYT:
	dc.w DATAG2L5RZ4HYT_0-DATAG2L5RZ4HYT, DATAG2L5RZ4HYT_1-DATAG2L5RZ4HYT
DATAG2L5RZ4HYT_0: dc.b $10
	dc.b $F4, $4, $40, $9B, $E0
	dc.b $F4, $4, $40, $9D, $F0
	dc.b $F4, $4, $40, $9D, $0
	dc.b $F4, $4, $40, $9F, $10
	dc.b $FC, $4, $40, $85, $E0
	dc.b $FC, $4, $40, $87, $F0
	dc.b $FC, $4, $40, $87, $0
	dc.b $FC, $4, $40, $89, $10
	dc.b $4, $4, $40, $8D, $E0
	dc.b $4, $4, $40, $8D, $10
	dc.b $C, $4, $40, $37, $E0
	dc.b $C, $4, $40, $37, $10
	dc.b $4, $4, $40, $8D, $F0
	dc.b $4, $4, $40, $8D, $0
	dc.b $C, $4, $40, $37, $F0
	dc.b $C, $4, $40, $37, $0
DATAG2L5RZ4HYT_1: dc.b $A
	dc.b $F4, $F, $0, $C5, $E0
	dc.b $4, $F, $0, $D5, $E0
	dc.b $24, $F, $0, $D5, $E0
	dc.b $44, $F, $0, $D5, $E0
	dc.b $64, $F, $0, $D5, $E0
	dc.b $F4, $F, $8, $C5, $0
	dc.b $4, $F, $8, $D5, $0
	dc.b $24, $F, $8, $D5, $0
	dc.b $44, $F, $8, $D5, $0
	dc.b $64, $F, $8, $D5, $0
	even