; ================================================================================
; Sprite Mappings - generated by Flex 2 Sat Jun 23 2018 11:38:25 GMT-0700 (Pacific Daylight Time)
; ================================================================================

DATASCN4DM1JX6L:
	dc.w DATASCN4DM1JX6L_0-DATASCN4DM1JX6L, DATASCN4DM1JX6L_1-DATASCN4DM1JX6L
DATASCN4DM1JX6L_0: dc.b $10
	dc.b $F4, $4, $1, $C9, $E0
	dc.b $F4, $4, $9, $C9, $10
	dc.b $F4, $0, $1, $CA, $F0
	dc.b $F4, $0, $1, $CA, $F8
	dc.b $F4, $0, $1, $CA, $0
	dc.b $F4, $0, $1, $CA, $8
	dc.b $FC, $C, $1, $CB, $E0
	dc.b $FC, $C, $1, $CB, $0
	dc.b $4, $C, $11, $CB, $E0
	dc.b $4, $C, $11, $CB, $0
	dc.b $C, $4, $1, $C9, $E0
	dc.b $C, $4, $9, $C9, $10
	dc.b $C, $0, $1, $CA, $F0
	dc.b $C, $0, $1, $CA, $F8
	dc.b $C, $0, $1, $CA, $0
	dc.b $C, $0, $1, $CA, $8
DATASCN4DM1JX6L_1: dc.b $A
	dc.b $F4, $F, $0, $C5, $E0
	dc.b $4, $F, $0, $D5, $E0
	dc.b $24, $F, $0, $D5, $E0
	dc.b $44, $F, $0, $D5, $E0
	dc.b $64, $F, $0, $D5, $E0
	dc.b $F4, $F, $8, $C5, $0
	dc.b $4, $F, $8, $D5, $0
	dc.b $24, $F, $8, $D5, $0
	dc.b $44, $F, $8, $D5, $0
	dc.b $64, $F, $8, $D5, $0
	even