; ================================================================================
; Sprite Mappings - generated by Flex 2 Sun Oct 21 2018 08:24:56 GMT-0700 (Pacific Daylight Time)
; ================================================================================

DATAO4S1WSZEYZ:
	dc.w DATAO4S1WSZEYZ_0-DATAO4S1WSZEYZ, DATAO4S1WSZEYZ_1-DATAO4S1WSZEYZ
	dc.w DATAO4S1WSZEYZ_2-DATAO4S1WSZEYZ, DATAO4S1WSZEYZ_3-DATAO4S1WSZEYZ
	dc.w DATAO4S1WSZEYZ_4-DATAO4S1WSZEYZ, DATAO4S1WSZEYZ_5-DATAO4S1WSZEYZ
	dc.w DATAO4S1WSZEYZ_6-DATAO4S1WSZEYZ, DATAO4S1WSZEYZ_7-DATAO4S1WSZEYZ
	dc.w DATAO4S1WSZEYZ_8-DATAO4S1WSZEYZ, DATAO4S1WSZEYZ_9-DATAO4S1WSZEYZ
	dc.w DATAO4S1WSZEYZ_A-DATAO4S1WSZEYZ, DATAO4S1WSZEYZ_B-DATAO4S1WSZEYZ
DATAO4S1WSZEYZ_0: dc.b $2
	dc.b $EF, $7, $0, $0, $F0
	dc.b $EF, $7, $8, $0, $0
DATAO4S1WSZEYZ_1: dc.b $4
	dc.b $F5, $1, $10, $8, $F8
	dc.b $F5, $1, $18, $8, $0
	dc.b $EF, $7, $0, $0, $F0
	dc.b $EF, $7, $8, $0, $0
DATAO4S1WSZEYZ_2: dc.b $4
	dc.b $F5, $1, $0, $8, $F8
	dc.b $F5, $1, $8, $8, $0
	dc.b $EF, $7, $0, $0, $F0
	dc.b $EF, $7, $8, $0, $0
DATAO4S1WSZEYZ_3: dc.b $3
	dc.b $F5, $5, $0, $A, $F8
	dc.b $EF, $7, $0, $0, $F0
	dc.b $EF, $7, $8, $0, $0
DATAO4S1WSZEYZ_4: dc.b $3
	dc.b $F5, $5, $0, $E, $F8
	dc.b $EF, $7, $0, $0, $F0
	dc.b $EF, $7, $8, $0, $0
DATAO4S1WSZEYZ_5: dc.b $3
	dc.b $F5, $5, $0, $16, $F8
	dc.b $EF, $7, $0, $0, $F0
	dc.b $EF, $7, $8, $0, $0
DATAO4S1WSZEYZ_6: dc.b $4
	dc.b $F5, $1, $8, $1A, $0
	dc.b $F5, $1, $0, $1A, $F8
	dc.b $EF, $7, $0, $0, $F0
	dc.b $EF, $7, $8, $0, $0
DATAO4S1WSZEYZ_7: dc.b $4
	dc.b $F5, $1, $0, $1C, $F8
	dc.b $F5, $1, $8, $1C, $0
	dc.b $EF, $7, $0, $0, $F0
	dc.b $EF, $7, $8, $0, $0
DATAO4S1WSZEYZ_8: dc.b $4
	dc.b $F5, $1, $0, $1E, $F8
	dc.b $F5, $1, $8, $1E, $0
	dc.b $EF, $7, $0, $0, $F0
	dc.b $EF, $7, $8, $0, $0
DATAO4S1WSZEYZ_9: dc.b $3
	dc.b $F5, $5, $0, $20, $F8
	dc.b $EF, $7, $0, $0, $F0
	dc.b $EF, $7, $8, $0, $0
DATAO4S1WSZEYZ_A: dc.b $3
	dc.b $F5, $5, $0, $12, $F8
	dc.b $EF, $7, $0, $0, $F0
	dc.b $EF, $7, $8, $0, $0
DATAO4S1WSZEYZ_B: dc.b $1
	dc.b $FF, $D, $0, $24, $F0
	even