; ================================================================================
; Sprite Mappings - generated by Flex 2 Sun Jun 24 2018 15:01:12 GMT-0700 (Pacific Daylight Time)
; ================================================================================

DATAHU1N3R6Q81S:
	dc.w DATAHU1N3R6Q81S_0-DATAHU1N3R6Q81S, DATAHU1N3R6Q81S_1-DATAHU1N3R6Q81S
DATAHU1N3R6Q81S_0: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAHU1N3R6Q81S_1: dc.b $1
	dc.b $F0, $F, $0, $10, $F0
	even