; ================================================================================
; Sprite Mappings - generated by Flex 2 Sun Jun 24 2018 15:46:27 GMT-0700 (Pacific Daylight Time)
; ================================================================================

DATA7N49SEAZF5N:
	dc.w DATA7N49SEAZF5N_0-DATA7N49SEAZF5N, DATA7N49SEAZF5N_1-DATA7N49SEAZF5N
	dc.w DATA7N49SEAZF5N_2-DATA7N49SEAZF5N, DATA7N49SEAZF5N_3-DATA7N49SEAZF5N
	dc.w DATA7N49SEAZF5N_4-DATA7N49SEAZF5N, DATA7N49SEAZF5N_5-DATA7N49SEAZF5N
DATA7N49SEAZF5N_0: dc.b $6
	dc.b $F4, $9, $0, $0, $E8
	dc.b $F4, $9, $0, $F, $0
	dc.b $4, $8, $0, $15, $E8
	dc.b $4, $4, $0, $18, $0
	dc.b $F1, $8, $0, $1A, $EC
	dc.b $F1, $4, $0, $1D, $4
DATA7N49SEAZF5N_1: dc.b $6
	dc.b $F4, $9, $0, $0, $E8
	dc.b $F4, $9, $0, $F, $0
	dc.b $4, $8, $0, $15, $E8
	dc.b $4, $4, $0, $18, $0
	dc.b $F4, $8, $0, $1F, $EC
	dc.b $F4, $4, $0, $22, $4
DATA7N49SEAZF5N_2: dc.b $7
	dc.b $4, $0, $0, $30, $C
	dc.b $F4, $9, $0, $0, $E8
	dc.b $F4, $9, $0, $F, $0
	dc.b $4, $8, $0, $15, $E8
	dc.b $4, $4, $0, $18, $0
	dc.b $F1, $8, $0, $1A, $EC
	dc.b $F1, $4, $0, $1D, $4
DATA7N49SEAZF5N_3: dc.b $7
	dc.b $4, $4, $0, $31, $C
	dc.b $F4, $9, $0, $0, $E8
	dc.b $F4, $9, $0, $F, $0
	dc.b $4, $8, $0, $15, $E8
	dc.b $4, $4, $0, $18, $0
	dc.b $F4, $8, $0, $1F, $EC
	dc.b $F4, $4, $0, $22, $4
DATA7N49SEAZF5N_4: dc.b $6
	dc.b $F4, $D, $0, $0, $EC
	dc.b $4, $C, $0, $8, $EC
	dc.b $4, $0, $0, $C, $C
	dc.b $C, $4, $0, $D, $F4
	dc.b $F1, $8, $0, $1A, $EC
	dc.b $F1, $4, $0, $1D, $4
DATA7N49SEAZF5N_5: dc.b $4
	dc.b $F4, $D, $0, $0, $EC
	dc.b $4, $C, $0, $8, $EC
	dc.b $4, $0, $0, $C, $C
	dc.b $C, $4, $0, $D, $F4
	even