; ================================================================================
; Sprite Mappings - generated by Flex 2 Tue Oct 09 2018 18:21:08 GMT-0700 (Pacific Daylight Time)
; ================================================================================

DATAAXCFZ76YASU:
	dc.w DATAAXCFZ76YASU_0-DATAAXCFZ76YASU, DATAAXCFZ76YASU_1-DATAAXCFZ76YASU
DATAAXCFZ76YASU_0: dc.b $1
	dc.b $F0, $F, $0, $8, $F0
DATAAXCFZ76YASU_1: dc.b $4
	dc.b $F0, $F, $0, $8, $C0
	dc.b $F0, $F, $0, $8, $E0
	dc.b $F0, $F, $0, $8, $0
	dc.b $F0, $F, $0, $8, $20
	even