; ================================================================================
; Sprite Mappings - generated by Flex 2 Mon Oct 08 2018 20:24:10 GMT-0700 (Pacific Daylight Time)
; ================================================================================

DATAWGHIKX447BI:
	dc.w DATAWGHIKX447BI_0-DATAWGHIKX447BI, DATAWGHIKX447BI_1-DATAWGHIKX447BI
	dc.w DATAWGHIKX447BI_2-DATAWGHIKX447BI
DATAWGHIKX447BI_0: dc.b $C
	dc.b $B8, $C, $0, $0, $E0
	dc.b $B8, $C, $8, $0, $0
	dc.b $C0, $F, $0, $4, $E0
	dc.b $C0, $F, $8, $4, $0
	dc.b $E0, $F, $0, $4, $E0
	dc.b $E0, $F, $8, $4, $0
	dc.b $0, $F, $0, $4, $E0
	dc.b $0, $F, $8, $4, $0
	dc.b $20, $F, $0, $4, $E0
	dc.b $20, $F, $8, $4, $0
	dc.b $40, $C, $10, $0, $E0
	dc.b $40, $C, $18, $0, $0
DATAWGHIKX447BI_1: dc.b $2
	dc.b $8, $6, $0, $14, $F0
	dc.b $0, $6, $0, $14, $0
DATAWGHIKX447BI_2: dc.b $A
	dc.b $C8, $C, $0, $0, $E0
	dc.b $C8, $C, $8, $0, $0
	dc.b $D0, $F, $0, $4, $E0
	dc.b $D0, $F, $8, $4, $0
	dc.b $F0, $F, $0, $4, $E0
	dc.b $F0, $F, $8, $4, $0
	dc.b $10, $F, $0, $4, $E0
	dc.b $10, $F, $8, $4, $0
	dc.b $30, $C, $10, $0, $E0
	dc.b $30, $C, $18, $0, $0
	even