; ================================================================================
; Sprite Mappings - generated by Flex 2 Sat Oct 20 2018 15:17:18 GMT-0700 (Pacific Daylight Time)
; ================================================================================

DATA9PRZ0HTOO7D:
	dc.w DATA9PRZ0HTOO7D_0-DATA9PRZ0HTOO7D, DATA9PRZ0HTOO7D_1-DATA9PRZ0HTOO7D
	dc.w DATA9PRZ0HTOO7D_2-DATA9PRZ0HTOO7D, DATA9PRZ0HTOO7D_3-DATA9PRZ0HTOO7D
	dc.w DATA9PRZ0HTOO7D_4-DATA9PRZ0HTOO7D, DATA9PRZ0HTOO7D_5-DATA9PRZ0HTOO7D
DATA9PRZ0HTOO7D_0: dc.b $2
	dc.b $F8, $C, $0, $0, $F0
	dc.b $0, $C, $0, $4, $F0
DATA9PRZ0HTOO7D_1: dc.b $1
	dc.b $0, $C, $0, $0, $F0
DATA9PRZ0HTOO7D_2: dc.b $3
	dc.b $E8, $C, $0, $0, $F0
	dc.b $F0, $5, $0, $8, $F8
	dc.b $0, $C, $0, $C, $F0
DATA9PRZ0HTOO7D_3: dc.b $1
	dc.b $F0, $7, $0, $0, $F8
DATA9PRZ0HTOO7D_4: dc.b $1
	dc.b $F0, $3, $0, $4, $F8
DATA9PRZ0HTOO7D_5: dc.b $4
	dc.b $F0, $3, $0, $4, $10
	dc.b $F8, $9, $0, $8, $F8
	dc.b $F0, $0, $0, $0, $F8
	dc.b $8, $0, $0, $3, $F8
	even