; ================================================================================
; Sprite Mappings - generated by Flex 2 Fri Jul 13 2018 22:40:39 GMT-0700 (Pacific Daylight Time)
; ================================================================================

DATA3ST796E0Q6T:
	dc.w DATA3ST796E0Q6T_0-DATA3ST796E0Q6T, DATA3ST796E0Q6T_1-DATA3ST796E0Q6T
	dc.w DATA3ST796E0Q6T_2-DATA3ST796E0Q6T
DATA3ST796E0Q6T_0: dc.b $2
	dc.b $F0, $7, $0, $0, $F0
	dc.b $F0, $7, $8, $0, $0
DATA3ST796E0Q6T_1: dc.b $2
	dc.b $F4, $6, $0, $8, $F4
	dc.b $F4, $2, $8, $8, $4
DATA3ST796E0Q6T_2: dc.b $2
	dc.b $F0, $7, $0, $E, $F0
	dc.b $F0, $7, $8, $E, $0
	even