; ================================================================================
; Sprite Mappings - generated by Flex 2 Sat Jun 23 2018 22:14:54 GMT-0700 (Pacific Daylight Time)
; ================================================================================

DATANR777NT90B:
	dc.w DATANR777NT90B_0-DATANR777NT90B, DATANR777NT90B_1-DATANR777NT90B
	dc.w DATANR777NT90B_2-DATANR777NT90B, DATANR777NT90B_3-DATANR777NT90B
	dc.w DATANR777NT90B_4-DATANR777NT90B, DATANR777NT90B_5-DATANR777NT90B
	dc.w DATANR777NT90B_6-DATANR777NT90B
DATANR777NT90B_0: dc.b $9
	dc.b $E7, $D, $0, $0, $F8
	dc.b $F7, $C, $0, $8, $F8
	dc.b $F7, $1, $0, $C, $E8
	dc.b $FF, $8, $0, $E, $0
	dc.b $E7, $3, $0, $11, $F0
	dc.b $FF, $0, $0, $15, $F8
	dc.b $EA, $0, $0, $1A, $E8
	dc.b $7, $5, $0, $16, $9
	dc.b $C, $4, $0, $1B, $F3
DATANR777NT90B_1: dc.b $9
	dc.b $E8, $D, $0, $0, $F8
	dc.b $F8, $C, $0, $8, $F8
	dc.b $F8, $1, $0, $C, $E8
	dc.b $0, $8, $0, $E, $0
	dc.b $E8, $3, $0, $11, $F0
	dc.b $0, $0, $0, $15, $F8
	dc.b $E9, $0, $0, $1A, $E8
	dc.b $8, $5, $0, $16, $B
	dc.b $E, $4, $0, $1B, $F2
DATANR777NT90B_2: dc.b $9
	dc.b $E9, $D, $0, $0, $F8
	dc.b $F9, $C, $0, $8, $F8
	dc.b $F9, $1, $0, $C, $E8
	dc.b $1, $8, $0, $E, $0
	dc.b $E9, $3, $0, $11, $F0
	dc.b $1, $0, $0, $15, $F8
	dc.b $E9, $0, $0, $1A, $E8
	dc.b $9, $5, $0, $16, $A
	dc.b $E, $4, $0, $1B, $EE
DATANR777NT90B_3: dc.b $0
DATANR777NT90B_4: dc.b $0
DATANR777NT90B_5: dc.b $0
DATANR777NT90B_6: dc.b $0
	even