; ================================================================================
; Sprite Mappings - generated by Flex 2 Sat Sep 01 2018 07:24:39 GMT-0700 (Pacific Daylight Time)
; ================================================================================

DATALLU3VB9WH7:
	dc.w DATALLU3VB9WH7_0-DATALLU3VB9WH7, DATALLU3VB9WH7_1-DATALLU3VB9WH7
	dc.w DATALLU3VB9WH7_2-DATALLU3VB9WH7, DATALLU3VB9WH7_3-DATALLU3VB9WH7
DATALLU3VB9WH7_0: dc.b $4
	dc.b $E8, $A, $0, $0, $E8
	dc.b $E8, $A, $0, $9, $0
	dc.b $0, $A, $0, $12, $E8
	dc.b $0, $A, $0, $1B, $0
DATALLU3VB9WH7_1: dc.b $4
	dc.b $E8, $A, $0, $0, $E8
	dc.b $E8, $A, $0, $9, $0
	dc.b $0, $A, $0, $12, $E8
	dc.b $0, $A, $0, $1B, $0
DATALLU3VB9WH7_2: dc.b $0
DATALLU3VB9WH7_3: dc.b $0
	even