; ================================================================================
; Sprite Mappings - generated by Flex 2 Sun Jun 24 2018 09:53:56 GMT-0700 (Pacific Daylight Time)
; ================================================================================

DATAGWZWV8Y0QWB:
	dc.w DATAGWZWV8Y0QWB_0-DATAGWZWV8Y0QWB, DATAGWZWV8Y0QWB_1-DATAGWZWV8Y0QWB
	dc.w DATAGWZWV8Y0QWB_2-DATAGWZWV8Y0QWB, DATAGWZWV8Y0QWB_3-DATAGWZWV8Y0QWB
	dc.w DATAGWZWV8Y0QWB_4-DATAGWZWV8Y0QWB, DATAGWZWV8Y0QWB_5-DATAGWZWV8Y0QWB
	dc.w DATAGWZWV8Y0QWB_6-DATAGWZWV8Y0QWB, DATAGWZWV8Y0QWB_7-DATAGWZWV8Y0QWB
	dc.w DATAGWZWV8Y0QWB_8-DATAGWZWV8Y0QWB, DATAGWZWV8Y0QWB_9-DATAGWZWV8Y0QWB
	dc.w DATAGWZWV8Y0QWB_A-DATAGWZWV8Y0QWB
DATAGWZWV8Y0QWB_0: dc.b $3
	dc.b $EC, $D, $0, $0, $EC
	dc.b $F4, $0, $0, $8, $C
	dc.b $FC, $E, $0, $9, $F4
DATAGWZWV8Y0QWB_1: dc.b $3
	dc.b $EC, $6, $0, $15, $EC
	dc.b $EC, $9, $0, $1B, $FC
	dc.b $FC, $A, $0, $21, $FC
DATAGWZWV8Y0QWB_2: dc.b $3
	dc.b $EC, $9, $0, $1B, $FC
	dc.b $FC, $A, $0, $21, $FC
	dc.b $EC, $6, $0, $15, $EC
DATAGWZWV8Y0QWB_3: dc.b $4
	dc.b $EC, $6, $0, $30, $EC
	dc.b $EC, $9, $0, $1B, $FC
	dc.b $FC, $9, $0, $36, $FC
	dc.b $C, $0, $0, $3C, $C
DATAGWZWV8Y0QWB_4: dc.b $3
	dc.b $F4, $D, $0, $3D, $EC
	dc.b $FC, $0, $0, $20, $C
	dc.b $4, $8, $0, $45, $FC
DATAGWZWV8Y0QWB_5: dc.b $2
	dc.b $F8, $D, $0, $48, $EC
	dc.b $F8, $1, $0, $50, $C
DATAGWZWV8Y0QWB_6: dc.b $3
	dc.b $F8, $D, $0, $48, $EC
	dc.b $F8, $1, $0, $50, $C
	dc.b $0, $0, $0, $52, $14
DATAGWZWV8Y0QWB_7: dc.b $3
	dc.b $F8, $D, $0, $48, $EC
	dc.b $F8, $1, $0, $50, $C
	dc.b $0, $4, $0, $53, $14
DATAGWZWV8Y0QWB_8: dc.b $3
	dc.b $F8, $D, $0, $48, $EC
	dc.b $F8, $1, $0, $50, $C
	dc.b $0, $0, $E0, $52, $14
DATAGWZWV8Y0QWB_9: dc.b $3
	dc.b $F8, $D, $0, $48, $EC
	dc.b $F8, $1, $0, $50, $C
	dc.b $0, $4, $E0, $53, $14
DATAGWZWV8Y0QWB_A: dc.b $0
	even