; ================================================================================
; Sprite Mappings - generated by Flex 2 Mon Jul 23 2018 09:07:04 GMT-0700 (Pacific Daylight Time)
; ================================================================================

DATA64NJH5PW2HK:
	dc.w DATA64NJH5PW2HK_0-DATA64NJH5PW2HK
DATA64NJH5PW2HK_0: dc.b $13
	dc.b $F8, $4, $1, $C9, $D8
	dc.b $F8, $4, $9, $C9, $18
	dc.b $F8, $0, $1, $CA, $E8
	dc.b $F8, $0, $1, $CA, $F0
	dc.b $F8, $0, $1, $CA, $F8
	dc.b $F8, $0, $1, $CA, $0
	dc.b $F8, $0, $1, $CA, $8
	dc.b $F8, $0, $1, $CA, $10
	dc.b $8, $C, $11, $CB, $F8
	dc.b $0, $C, $1, $CB, $F8
	dc.b $10, $4, $9, $C9, $18
	dc.b $10, $4, $1, $C9, $E8
	dc.b $10, $0, $1, $CA, $10
	dc.b $10, $0, $1, $CA, $8
	dc.b $10, $0, $1, $CA, $0
	dc.b $10, $0, $1, $CA, $F8
	dc.b $0, $0, $11, $E7, $F0
	dc.b $8, $0, $19, $E7, $18
	dc.b $0, $0, $9, $E7, $18
	even