; ================================================================================
; Sprite Mappings - generated by Flex 2 Mon Jul 09 2018 12:13:44 GMT-0700 (Pacific Daylight Time)
; ================================================================================

DATA6JW42Z3S7HT:
	dc.w DATA6JW42Z3S7HT_0-DATA6JW42Z3S7HT, DATA6JW42Z3S7HT_1-DATA6JW42Z3S7HT
	dc.w DATA6JW42Z3S7HT_2-DATA6JW42Z3S7HT, DATA6JW42Z3S7HT_3-DATA6JW42Z3S7HT
	dc.w DATA6JW42Z3S7HT_4-DATA6JW42Z3S7HT, DATA6JW42Z3S7HT_5-DATA6JW42Z3S7HT
	dc.w DATA6JW42Z3S7HT_6-DATA6JW42Z3S7HT, DATA6JW42Z3S7HT_7-DATA6JW42Z3S7HT
	dc.w DATA6JW42Z3S7HT_8-DATA6JW42Z3S7HT, DATA6JW42Z3S7HT_9-DATA6JW42Z3S7HT
	dc.w DATA6JW42Z3S7HT_A-DATA6JW42Z3S7HT, DATA6JW42Z3S7HT_B-DATA6JW42Z3S7HT
DATA6JW42Z3S7HT_0: dc.b $3
	dc.b $F1, $A, $0, $0, $F4
	dc.b $9, $8, $0, $12, $F4
	dc.b $E7, $1, $0, $21, $FC
DATA6JW42Z3S7HT_1: dc.b $3
	dc.b $F1, $A, $0, $9, $F4
	dc.b $9, $8, $0, $12, $F4
	dc.b $E7, $1, $0, $21, $FC
DATA6JW42Z3S7HT_2: dc.b $3
	dc.b $F0, $A, $0, $0, $F4
	dc.b $8, $8, $0, $15, $F4
	dc.b $E6, $1, $0, $21, $FC
DATA6JW42Z3S7HT_3: dc.b $3
	dc.b $F1, $A, $0, $9, $F4
	dc.b $9, $8, $0, $18, $F4
	dc.b $E7, $1, $0, $21, $FC
DATA6JW42Z3S7HT_4: dc.b $3
	dc.b $F0, $A, $0, $0, $F4
	dc.b $8, $8, $0, $1B, $F4
	dc.b $E6, $1, $0, $21, $FC
DATA6JW42Z3S7HT_5: dc.b $3
	dc.b $F1, $A, $0, $9, $F4
	dc.b $9, $8, $0, $1E, $F4
	dc.b $E7, $1, $0, $21, $FC
DATA6JW42Z3S7HT_6: dc.b $2
	dc.b $F1, $A, $0, $0, $F4
	dc.b $9, $8, $0, $12, $F4
DATA6JW42Z3S7HT_7: dc.b $2
	dc.b $F1, $A, $0, $9, $F4
	dc.b $9, $8, $0, $12, $F4
DATA6JW42Z3S7HT_8: dc.b $1
	dc.b $E7, $1, $0, $23, $FC
DATA6JW42Z3S7HT_9: dc.b $1
	dc.b $E7, $1, $0, $25, $FC
DATA6JW42Z3S7HT_A: dc.b $1
	dc.b $FC, $0, $0, $27, $FC
DATA6JW42Z3S7HT_B: dc.b $1
	dc.b $FC, $0, $0, $28, $FC
	even