; ================================================================================
; Sprite Mappings - generated by Flex 2 Sun Jul 08 2018 13:32:13 GMT-0700 (Pacific Daylight Time)
; ================================================================================

DATAGXN9UGOMTAN:
	dc.w DATAGXN9UGOMTAN_0-DATAGXN9UGOMTAN, DATAGXN9UGOMTAN_1-DATAGXN9UGOMTAN
	dc.w DATAGXN9UGOMTAN_2-DATAGXN9UGOMTAN, DATAGXN9UGOMTAN_3-DATAGXN9UGOMTAN
	dc.w DATAGXN9UGOMTAN_4-DATAGXN9UGOMTAN, DATAGXN9UGOMTAN_5-DATAGXN9UGOMTAN
DATAGXN9UGOMTAN_0: dc.b $12
	dc.b $EC, $4, $0, $F, $FC
	dc.b $F4, $0, $0, $11, $C
	dc.b $F4, $8, $0, $0, $F4
	dc.b $FC, $0, $0, $3, $EC
	dc.b $FC, $0, $0, $6, $F4
	dc.b $FC, $0, $0, $9, $FC
	dc.b $FC, $0, $0, $C, $4
	dc.b $FC, $0, $0, $12, $C
	dc.b $4, $0, $0, $13, $C
	dc.b $4, $0, $0, $4, $EC
	dc.b $C, $0, $0, $5, $EC
	dc.b $4, $0, $0, $7, $F4
	dc.b $C, $0, $0, $8, $F4
	dc.b $4, $0, $0, $A, $FC
	dc.b $C, $0, $0, $B, $FC
	dc.b $4, $0, $0, $D, $4
	dc.b $C, $0, $0, $E, $4
	dc.b $5, $9, $0, $37, $DA
DATAGXN9UGOMTAN_1: dc.b $12
	dc.b $EC, $4, $0, $F, $FC
	dc.b $F4, $0, $0, $11, $C
	dc.b $F4, $8, $0, $0, $F4
	dc.b $FC, $0, $0, $3, $EC
	dc.b $FC, $0, $0, $6, $F4
	dc.b $FC, $0, $0, $9, $FC
	dc.b $FC, $0, $0, $C, $4
	dc.b $FC, $0, $0, $12, $C
	dc.b $4, $0, $0, $13, $C
	dc.b $4, $0, $0, $4, $EC
	dc.b $C, $0, $0, $5, $EC
	dc.b $4, $0, $0, $7, $F4
	dc.b $C, $0, $0, $8, $F4
	dc.b $4, $0, $0, $A, $FC
	dc.b $C, $0, $0, $B, $FC
	dc.b $4, $0, $0, $D, $4
	dc.b $C, $0, $0, $E, $4
	dc.b $4, $9, $0, $37, $D8
DATAGXN9UGOMTAN_2: dc.b $12
	dc.b $EC, $4, $0, $F, $FC
	dc.b $F4, $0, $0, $11, $C
	dc.b $F4, $8, $0, $0, $F4
	dc.b $FC, $0, $0, $3, $EC
	dc.b $FC, $0, $0, $6, $F4
	dc.b $FC, $0, $0, $9, $FC
	dc.b $FC, $0, $0, $C, $4
	dc.b $FC, $0, $0, $12, $C
	dc.b $4, $0, $0, $13, $C
	dc.b $4, $0, $0, $4, $EC
	dc.b $C, $0, $0, $5, $EC
	dc.b $4, $0, $0, $7, $F4
	dc.b $C, $0, $0, $8, $F4
	dc.b $4, $0, $0, $A, $FC
	dc.b $C, $0, $0, $B, $FC
	dc.b $4, $0, $0, $D, $4
	dc.b $C, $0, $0, $E, $4
	dc.b $2, $9, $0, $37, $D6
DATAGXN9UGOMTAN_3: dc.b $12
	dc.b $EC, $4, $0, $F, $FC
	dc.b $F4, $0, $0, $11, $C
	dc.b $F4, $8, $0, $0, $F4
	dc.b $FC, $0, $0, $3, $EC
	dc.b $FC, $0, $0, $6, $F4
	dc.b $FC, $0, $0, $9, $FC
	dc.b $FC, $0, $0, $C, $4
	dc.b $FC, $0, $0, $12, $C
	dc.b $4, $0, $0, $13, $C
	dc.b $4, $0, $0, $4, $EC
	dc.b $C, $0, $0, $5, $EC
	dc.b $4, $0, $0, $7, $F4
	dc.b $C, $0, $0, $8, $F4
	dc.b $4, $0, $0, $A, $FC
	dc.b $C, $0, $0, $B, $FC
	dc.b $4, $0, $0, $D, $4
	dc.b $C, $0, $0, $E, $4
	dc.b $0, $9, $0, $37, $D6
DATAGXN9UGOMTAN_4: dc.b $12
	dc.b $EC, $4, $0, $F, $FC
	dc.b $F4, $0, $0, $11, $C
	dc.b $F4, $8, $0, $0, $F4
	dc.b $FC, $0, $0, $3, $EC
	dc.b $FC, $0, $0, $6, $F4
	dc.b $FC, $0, $0, $9, $FC
	dc.b $FC, $0, $0, $C, $4
	dc.b $FC, $0, $0, $12, $C
	dc.b $4, $0, $0, $13, $C
	dc.b $4, $0, $0, $4, $EC
	dc.b $C, $0, $0, $5, $EC
	dc.b $4, $0, $0, $7, $F4
	dc.b $C, $0, $0, $8, $F4
	dc.b $4, $0, $0, $A, $FC
	dc.b $C, $0, $0, $B, $FC
	dc.b $4, $0, $0, $D, $4
	dc.b $C, $0, $0, $E, $4
	dc.b $1, $9, $0, $37, $D9
DATAGXN9UGOMTAN_5: dc.b $12
	dc.b $EC, $4, $0, $F, $FC
	dc.b $F4, $0, $0, $11, $C
	dc.b $F4, $8, $0, $0, $F4
	dc.b $FC, $0, $0, $3, $EC
	dc.b $FC, $0, $0, $6, $F4
	dc.b $FC, $0, $0, $9, $FC
	dc.b $FC, $0, $0, $C, $4
	dc.b $FC, $0, $0, $12, $C
	dc.b $4, $0, $0, $13, $C
	dc.b $4, $0, $0, $4, $EC
	dc.b $C, $0, $0, $5, $EC
	dc.b $4, $0, $0, $7, $F4
	dc.b $C, $0, $0, $8, $F4
	dc.b $4, $0, $0, $A, $FC
	dc.b $C, $0, $0, $B, $FC
	dc.b $4, $0, $0, $D, $4
	dc.b $C, $0, $0, $E, $4
	dc.b $3, $9, $0, $37, $D9
	even