; ================================================================================
; Sprite Mappings - generated by Flex 2 Sat Jul 07 2018 22:17:10 GMT-0700 (Pacific Daylight Time)
; ================================================================================

DATAP0DRQAN1UV:
	dc.w DATAP0DRQAN1UV_0-DATAP0DRQAN1UV, DATAP0DRQAN1UV_1-DATAP0DRQAN1UV
	dc.w DATAP0DRQAN1UV_2-DATAP0DRQAN1UV, DATAP0DRQAN1UV_3-DATAP0DRQAN1UV
DATAP0DRQAN1UV_0: dc.b $1
	dc.b $F4, $A, $0, $0, $F4
DATAP0DRQAN1UV_1: dc.b $1
	dc.b $F4, $A, $20, $9, $F4
DATAP0DRQAN1UV_2: dc.b $1
	dc.b $F4, $A, $0, $12, $F4
DATAP0DRQAN1UV_3: dc.b $1
	dc.b $F8, $5, $0, $1B, $F8
	even