; ================================================================================
; Sprite Mappings - generated by Flex 2 Sun Oct 21 2018 09:07:25 GMT-0700 (Pacific Daylight Time)
; ================================================================================

DATAC9132VBCWZV:
	dc.w DATAC9132VBCWZV_0-DATAC9132VBCWZV, DATAC9132VBCWZV_1-DATAC9132VBCWZV
	dc.w DATAC9132VBCWZV_2-DATAC9132VBCWZV, DATAC9132VBCWZV_3-DATAC9132VBCWZV
DATAC9132VBCWZV_0: dc.b $6
	dc.b $E4, $1, $0, $0, $F8
	dc.b $E4, $1, $8, $0, $0
	dc.b $F4, $3, $0, $2, $F8
	dc.b $F4, $3, $8, $2, $0
	dc.b $D4, $1, $0, $6, $F8
	dc.b $D4, $1, $8, $6, $0
DATAC9132VBCWZV_1: dc.b $4
	dc.b $E4, $1, $0, $0, $F8
	dc.b $E4, $1, $8, $0, $0
	dc.b $F4, $3, $0, $2, $F8
	dc.b $F4, $3, $8, $2, $0
DATAC9132VBCWZV_2: dc.b $2
	dc.b $F8, $1, $0, $8, $F8
	dc.b $F8, $1, $8, $8, $0
DATAC9132VBCWZV_3: dc.b $6
	dc.b $E4, $1, $0, $0, $F8
	dc.b $E4, $1, $8, $0, $0
	dc.b $F4, $3, $0, $2, $F8
	dc.b $F4, $3, $8, $2, $0
	dc.b $D4, $1, $0, $8, $F8
	dc.b $D4, $1, $8, $8, $0
	even