; ================================================================================
; Sprite Mappings - generated by Flex 2 Sat Sep 01 2018 11:10:27 GMT-0700 (Pacific Daylight Time)
; ================================================================================

DATA92SMZ176TU9:
	dc.w DATA92SMZ176TU9_0-DATA92SMZ176TU9, DATA92SMZ176TU9_1-DATA92SMZ176TU9
	dc.w DATA92SMZ176TU9_2-DATA92SMZ176TU9, DATA92SMZ176TU9_3-DATA92SMZ176TU9
	dc.w DATA92SMZ176TU9_4-DATA92SMZ176TU9, DATA92SMZ176TU9_5-DATA92SMZ176TU9
	dc.w DATA92SMZ176TU9_6-DATA92SMZ176TU9, DATA92SMZ176TU9_7-DATA92SMZ176TU9
	dc.w DATA92SMZ176TU9_8-DATA92SMZ176TU9, DATA92SMZ176TU9_9-DATA92SMZ176TU9
	dc.w DATA92SMZ176TU9_A-DATA92SMZ176TU9, DATA92SMZ176TU9_B-DATA92SMZ176TU9
DATA92SMZ176TU9_0: dc.b $3
	dc.b $FC, $0, $0, $8F, $E8
	dc.b $E8, $E, $0, $0, $F0
	dc.b $0, $F, $0, $6F, $F0
DATA92SMZ176TU9_1: dc.b $3
	dc.b $FC, $0, $0, $8F, $E8
	dc.b $E8, $E, $0, $0, $F0
	dc.b $0, $F, $0, $6F, $F0
DATA92SMZ176TU9_2: dc.b $3
	dc.b $FC, $0, $0, $8F, $E8
	dc.b $E8, $E, $0, $0, $F0
	dc.b $0, $F, $0, $6F, $F0
DATA92SMZ176TU9_3: dc.b $3
	dc.b $FC, $0, $0, $8F, $E8
	dc.b $E8, $E, $0, $0, $F0
	dc.b $0, $F, $0, $6F, $F0
DATA92SMZ176TU9_4: dc.b $3
	dc.b $FC, $0, $0, $8F, $E8
	dc.b $E8, $E, $0, $0, $F0
	dc.b $0, $F, $0, $6F, $F0
DATA92SMZ176TU9_5: dc.b $0
DATA92SMZ176TU9_6: dc.b $0
DATA92SMZ176TU9_7: dc.b $0
DATA92SMZ176TU9_8: dc.b $0
DATA92SMZ176TU9_9: dc.b $0
DATA92SMZ176TU9_A: dc.b $0
DATA92SMZ176TU9_B: dc.b $0
	even