; ================================================================================
; Sprite Mappings - generated by Flex 2 Sat Sep 01 2018 15:41:47 GMT-0700 (Pacific Daylight Time)
; ================================================================================

DATA1U6S2PL78VA:
	dc.w DATA1U6S2PL78VA_0-DATA1U6S2PL78VA, DATA1U6S2PL78VA_1-DATA1U6S2PL78VA
	dc.w DATA1U6S2PL78VA_2-DATA1U6S2PL78VA, DATA1U6S2PL78VA_3-DATA1U6S2PL78VA
	dc.w DATA1U6S2PL78VA_4-DATA1U6S2PL78VA, DATA1U6S2PL78VA_5-DATA1U6S2PL78VA
	dc.w DATA1U6S2PL78VA_6-DATA1U6S2PL78VA, DATA1U6S2PL78VA_7-DATA1U6S2PL78VA
	dc.w DATA1U6S2PL78VA_8-DATA1U6S2PL78VA, DATA1U6S2PL78VA_9-DATA1U6S2PL78VA
	dc.w DATA1U6S2PL78VA_A-DATA1U6S2PL78VA, DATA1U6S2PL78VA_B-DATA1U6S2PL78VA
	dc.w DATA1U6S2PL78VA_C-DATA1U6S2PL78VA
DATA1U6S2PL78VA_0: dc.b $6
	dc.b $A0, $D, $0, $0, $E0
	dc.b $A0, $D, $8, $0, $0
	dc.b $B0, $C, $0, $8, $E0
	dc.b $B0, $C, $0, $C, $0
	dc.b $B8, $F, $0, $10, $E0
	dc.b $B8, $F, $8, $10, $0
DATA1U6S2PL78VA_1: dc.b $8
	dc.b $A0, $D, $0, $0, $E0
	dc.b $A0, $D, $8, $0, $0
	dc.b $B0, $C, $0, $8, $E0
	dc.b $B0, $C, $0, $C, $0
	dc.b $B8, $F, $0, $10, $E0
	dc.b $B8, $F, $8, $10, $0
	dc.b $D8, $F, $0, $20, $E0
	dc.b $D8, $F, $8, $20, $0
DATA1U6S2PL78VA_2: dc.b $A
	dc.b $A0, $D, $0, $0, $E0
	dc.b $A0, $D, $8, $0, $0
	dc.b $B0, $C, $0, $8, $E0
	dc.b $B0, $C, $0, $C, $0
	dc.b $B8, $F, $0, $10, $E0
	dc.b $B8, $F, $8, $10, $0
	dc.b $D8, $F, $0, $20, $E0
	dc.b $D8, $F, $8, $20, $0
	dc.b $F8, $F, $0, $30, $E0
	dc.b $F8, $F, $8, $30, $0
DATA1U6S2PL78VA_3: dc.b $C
	dc.b $A0, $D, $0, $0, $E0
	dc.b $A0, $D, $8, $0, $0
	dc.b $B0, $C, $0, $8, $E0
	dc.b $B0, $C, $0, $C, $0
	dc.b $B8, $F, $0, $10, $E0
	dc.b $B8, $F, $8, $10, $0
	dc.b $D8, $F, $0, $20, $E0
	dc.b $D8, $F, $8, $20, $0
	dc.b $F8, $F, $0, $30, $E0
	dc.b $F8, $F, $8, $30, $0
	dc.b $18, $F, $0, $40, $E0
	dc.b $18, $F, $8, $40, $0
DATA1U6S2PL78VA_4: dc.b $D
	dc.b $A0, $D, $0, $0, $E0
	dc.b $A0, $D, $8, $0, $0
	dc.b $B0, $C, $0, $8, $E0
	dc.b $B0, $C, $0, $C, $0
	dc.b $B8, $F, $0, $10, $E0
	dc.b $B8, $F, $8, $10, $0
	dc.b $D8, $F, $0, $20, $E0
	dc.b $D8, $F, $8, $20, $0
	dc.b $F8, $F, $0, $30, $E0
	dc.b $F8, $F, $8, $30, $0
	dc.b $18, $F, $0, $40, $E0
	dc.b $18, $F, $8, $40, $0
	dc.b $38, $F, $0, $50, $F0
DATA1U6S2PL78VA_5: dc.b $E
	dc.b $A0, $D, $0, $0, $E0
	dc.b $A0, $D, $8, $0, $0
	dc.b $B0, $C, $0, $8, $E0
	dc.b $B0, $C, $0, $C, $0
	dc.b $B8, $F, $0, $10, $E0
	dc.b $B8, $F, $8, $10, $0
	dc.b $D8, $F, $0, $20, $E0
	dc.b $D8, $F, $8, $20, $0
	dc.b $F8, $F, $0, $30, $E0
	dc.b $F8, $F, $8, $30, $0
	dc.b $18, $F, $0, $40, $E0
	dc.b $18, $F, $8, $40, $0
	dc.b $38, $F, $0, $50, $F0
	dc.b $58, $F, $0, $50, $F0
DATA1U6S2PL78VA_6: dc.b $E
	dc.b $A0, $D, $0, $0, $E0
	dc.b $A0, $D, $8, $0, $0
	dc.b $B0, $C, $0, $8, $E0
	dc.b $B0, $C, $0, $C, $0
	dc.b $B8, $F, $0, $10, $E0
	dc.b $B8, $F, $8, $10, $0
	dc.b $D8, $F, $0, $20, $E0
	dc.b $D8, $F, $8, $20, $0
	dc.b $F8, $F, $0, $30, $E0
	dc.b $F8, $F, $8, $30, $0
	dc.b $18, $F, $0, $40, $E0
	dc.b $18, $F, $8, $40, $0
	dc.b $38, $F, $0, $50, $F0
	dc.b $58, $F, $0, $50, $F0
DATA1U6S2PL78VA_7: dc.b $E
	dc.b $A0, $D, $0, $0, $E0
	dc.b $A0, $D, $8, $0, $0
	dc.b $B0, $C, $0, $8, $E0
	dc.b $B0, $C, $0, $C, $0
	dc.b $B8, $F, $0, $10, $E0
	dc.b $B8, $F, $8, $10, $0
	dc.b $D8, $F, $0, $20, $E0
	dc.b $D8, $F, $8, $20, $0
	dc.b $F8, $F, $0, $30, $E0
	dc.b $F8, $F, $8, $30, $0
	dc.b $18, $F, $0, $40, $E0
	dc.b $18, $F, $8, $40, $0
	dc.b $38, $F, $0, $50, $F0
	dc.b $58, $F, $0, $50, $F0
DATA1U6S2PL78VA_8: dc.b $E
	dc.b $A0, $D, $0, $0, $E0
	dc.b $A0, $D, $8, $0, $0
	dc.b $B0, $C, $0, $8, $E0
	dc.b $B0, $C, $0, $C, $0
	dc.b $B8, $F, $0, $10, $E0
	dc.b $B8, $F, $8, $10, $0
	dc.b $D8, $F, $0, $20, $E0
	dc.b $D8, $F, $8, $20, $0
	dc.b $F8, $F, $0, $30, $E0
	dc.b $F8, $F, $8, $30, $0
	dc.b $18, $F, $0, $40, $E0
	dc.b $18, $F, $8, $40, $0
	dc.b $38, $F, $0, $50, $F0
	dc.b $58, $F, $0, $50, $F0
DATA1U6S2PL78VA_9: dc.b $E
	dc.b $A0, $D, $0, $0, $E0
	dc.b $A0, $D, $8, $0, $0
	dc.b $B0, $C, $8, $8, $0
	dc.b $B0, $C, $8, $C, $E0
	dc.b $B8, $F, $0, $10, $E0
	dc.b $B8, $F, $8, $10, $0
	dc.b $D8, $F, $0, $20, $E0
	dc.b $D8, $F, $8, $20, $0
	dc.b $F8, $F, $0, $30, $E0
	dc.b $F8, $F, $8, $30, $0
	dc.b $18, $F, $0, $40, $E0
	dc.b $18, $F, $8, $40, $0
	dc.b $38, $F, $0, $50, $F0
	dc.b $58, $F, $0, $50, $F0
DATA1U6S2PL78VA_A: dc.b $E
	dc.b $A0, $D, $0, $0, $E0
	dc.b $A0, $D, $8, $0, $0
	dc.b $B0, $C, $0, $8, $E0
	dc.b $B0, $C, $0, $C, $0
	dc.b $B8, $F, $0, $10, $E0
	dc.b $B8, $F, $8, $10, $0
	dc.b $D8, $F, $0, $20, $E0
	dc.b $D8, $F, $8, $20, $0
	dc.b $F8, $F, $0, $30, $E0
	dc.b $F8, $F, $8, $30, $0
	dc.b $18, $F, $0, $40, $E0
	dc.b $18, $F, $8, $40, $0
	dc.b $38, $F, $0, $50, $F0
	dc.b $58, $F, $0, $50, $F0
DATA1U6S2PL78VA_B: dc.b $0
DATA1U6S2PL78VA_C: dc.b $2
	dc.b $D0, $D, $0, $6E, $E5
	dc.b $D0, $5, $0, $76, $5
	even