; ================================================================================
; Sprite Mappings - generated by Flex 2 Fri Sep 07 2018 20:27:38 GMT-0700 (Pacific Daylight Time)
; ================================================================================

DATAHQKXO4QZ259:
	dc.w $0, DATAHQKXO4QZ259_1-DATAHQKXO4QZ259
	dc.w $0, $0
	dc.w $0, $0
	dc.w DATAHQKXO4QZ259_6-DATAHQKXO4QZ259, DATAHQKXO4QZ259_7-DATAHQKXO4QZ259
	dc.w DATAHQKXO4QZ259_8-DATAHQKXO4QZ259, DATAHQKXO4QZ259_9-DATAHQKXO4QZ259
	dc.w DATAHQKXO4QZ259_A-DATAHQKXO4QZ259, DATAHQKXO4QZ259_B-DATAHQKXO4QZ259
	dc.w DATAHQKXO4QZ259_C-DATAHQKXO4QZ259, DATAHQKXO4QZ259_D-DATAHQKXO4QZ259
	dc.w DATAHQKXO4QZ259_E-DATAHQKXO4QZ259, DATAHQKXO4QZ259_F-DATAHQKXO4QZ259
	dc.w DATAHQKXO4QZ259_10-DATAHQKXO4QZ259, DATAHQKXO4QZ259_11-DATAHQKXO4QZ259
	dc.w DATAHQKXO4QZ259_12-DATAHQKXO4QZ259, DATAHQKXO4QZ259_13-DATAHQKXO4QZ259
	dc.w DATAHQKXO4QZ259_14-DATAHQKXO4QZ259, DATAHQKXO4QZ259_15-DATAHQKXO4QZ259
	dc.w DATAHQKXO4QZ259_16-DATAHQKXO4QZ259, DATAHQKXO4QZ259_17-DATAHQKXO4QZ259
	dc.w DATAHQKXO4QZ259_18-DATAHQKXO4QZ259, DATAHQKXO4QZ259_19-DATAHQKXO4QZ259
	dc.w DATAHQKXO4QZ259_1A-DATAHQKXO4QZ259, DATAHQKXO4QZ259_1B-DATAHQKXO4QZ259
	dc.w DATAHQKXO4QZ259_1C-DATAHQKXO4QZ259, DATAHQKXO4QZ259_1D-DATAHQKXO4QZ259
	dc.w DATAHQKXO4QZ259_1E-DATAHQKXO4QZ259, DATAHQKXO4QZ259_1F-DATAHQKXO4QZ259
	dc.w DATAHQKXO4QZ259_20-DATAHQKXO4QZ259, DATAHQKXO4QZ259_21-DATAHQKXO4QZ259
	dc.w DATAHQKXO4QZ259_22-DATAHQKXO4QZ259, DATAHQKXO4QZ259_23-DATAHQKXO4QZ259
	dc.w DATAHQKXO4QZ259_24-DATAHQKXO4QZ259, DATAHQKXO4QZ259_25-DATAHQKXO4QZ259
	dc.w DATAHQKXO4QZ259_26-DATAHQKXO4QZ259, DATAHQKXO4QZ259_27-DATAHQKXO4QZ259
	dc.w DATAHQKXO4QZ259_28-DATAHQKXO4QZ259, DATAHQKXO4QZ259_29-DATAHQKXO4QZ259
	dc.w DATAHQKXO4QZ259_2A-DATAHQKXO4QZ259, DATAHQKXO4QZ259_2B-DATAHQKXO4QZ259
	dc.w DATAHQKXO4QZ259_2C-DATAHQKXO4QZ259, DATAHQKXO4QZ259_2D-DATAHQKXO4QZ259
	dc.w DATAHQKXO4QZ259_2E-DATAHQKXO4QZ259, DATAHQKXO4QZ259_2F-DATAHQKXO4QZ259
	dc.w DATAHQKXO4QZ259_30-DATAHQKXO4QZ259, DATAHQKXO4QZ259_31-DATAHQKXO4QZ259
	dc.w DATAHQKXO4QZ259_32-DATAHQKXO4QZ259, $0
	dc.w $0, $0
	dc.w $0, $0
	dc.w DATAHQKXO4QZ259_38-DATAHQKXO4QZ259, $0
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, $0
	dc.w DATAHQKXO4QZ259_4C-DATAHQKXO4QZ259, $0
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, DATAHQKXO4QZ259_55-DATAHQKXO4QZ259
	dc.w $0, $0
DATAHQKXO4QZ259_1: dc.b $8
	dc.b $EC, $8, $0, $0, $F0
	dc.b $F4, $D, $0, $3, $F0
	dc.b $4, $8, $0, $B, $F0
	dc.b $C, $8, $0, $E, $F8
	dc.b $EC, $0, $0, $11, $8
	dc.b $C, $0, $0, $12, $F0
	dc.b $4, $0, $0, $13, $8
	dc.b $CC, $F, $0, $14, $F0
DATAHQKXO4QZ259_6: dc.b $9
	dc.b $F2, $F, $0, $0, $FC
	dc.b $D2, $3, $0, $10, $C
	dc.b $E2, $1, $0, $14, $14
	dc.b $D2, $3, $0, $16, $4
	dc.b $DA, $2, $0, $1A, $FC
	dc.b $E2, $1, $0, $1D, $E4
	dc.b $DA, $5, $0, $1F, $EC
	dc.b $EA, $0, $0, $23, $EC
	dc.b $F2, $E, $0, $24, $DC
DATAHQKXO4QZ259_7: dc.b $8
	dc.b $FB, $E, $0, $0, $F3
	dc.b $EB, $D, $0, $C, $F3
	dc.b $F3, $3, $0, $14, $EB
	dc.b $E3, $1, $0, $18, $EB
	dc.b $E3, $C, $0, $1A, $F3
	dc.b $FB, $0, $0, $1E, $13
	dc.b $3, $0, $0, $1F, $E3
	dc.b $D3, $5, $0, $20, $3
DATAHQKXO4QZ259_8: dc.b $8
	dc.b $ED, $9, $0, $0, $FA
	dc.b $FD, $A, $0, $6, $FA
	dc.b $D, $0, $0, $F, $12
	dc.b $D5, $2, $0, $10, $A
	dc.b $D, $0, $0, $13, $F2
	dc.b $D5, $2, $0, $14, $2
	dc.b $E5, $0, $0, $17, $FA
	dc.b $ED, $1, $0, $18, $F2
DATAHQKXO4QZ259_9: dc.b $B
	dc.b $FB, $9, $0, $0, $EA
	dc.b $B, $C, $0, $6, $EA
	dc.b $EB, $3, $0, $A, $2
	dc.b $EB, $9, $0, $E, $EA
	dc.b $EB, $3, $0, $14, $E2
	dc.b $F3, $3, $0, $18, $DA
	dc.b $E3, $3, $0, $1C, $12
	dc.b $3, $1, $0, $20, $12
	dc.b $DB, $9, $0, $22, $EA
	dc.b $D3, $6, $0, $28, $2
	dc.b $EB, $3, $0, $2E, $A
DATAHQKXO4QZ259_A: dc.b $8
	dc.b $ED, $9, $0, $0, $FA
	dc.b $FD, $A, $0, $6, $FA
	dc.b $D, $0, $0, $F, $12
	dc.b $D5, $2, $0, $10, $A
	dc.b $D, $0, $0, $13, $F2
	dc.b $D5, $2, $0, $14, $2
	dc.b $E5, $0, $0, $17, $FA
	dc.b $ED, $1, $0, $18, $F2
DATAHQKXO4QZ259_B: dc.b $8
	dc.b $FB, $E, $0, $0, $F3
	dc.b $EB, $D, $0, $C, $F3
	dc.b $F3, $3, $0, $14, $EB
	dc.b $E3, $1, $0, $18, $EB
	dc.b $E3, $C, $0, $1A, $F3
	dc.b $FB, $0, $0, $1E, $13
	dc.b $3, $0, $0, $1F, $E3
	dc.b $D3, $5, $0, $20, $3
DATAHQKXO4QZ259_C: dc.b $D
	dc.b $DD, $9, $0, $0, $F8
	dc.b $DD, $1, $0, $6, $10
	dc.b $ED, $D, $0, $8, $0
	dc.b $FD, $8, $0, $10, $8
	dc.b $ED, $0, $0, $13, $F8
	dc.b $FD, $4, $0, $14, $F8
	dc.b $F5, $0, $0, $16, $F8
	dc.b $D5, $8, $0, $17, $E8
	dc.b $DD, $7, $0, $1A, $E8
	dc.b $E5, $3, $0, $22, $E0
	dc.b $FD, $4, $0, $26, $E8
	dc.b $5, $9, $0, $28, $E8
	dc.b $15, $4, $0, $2E, $E8
DATAHQKXO4QZ259_D: dc.b $7
	dc.b $F0, $7, $0, $0, $5
	dc.b $D0, $4, $0, $8, $ED
	dc.b $F8, $1, $0, $A, $15
	dc.b $0, $0, $0, $C, $FD
	dc.b $E0, $B, $0, $D, $ED
	dc.b $D8, $8, $0, $19, $ED
	dc.b $E8, $4, $0, $1C, $5
DATAHQKXO4QZ259_E: dc.b $D
	dc.b $DD, $9, $0, $0, $F8
	dc.b $DD, $1, $0, $6, $10
	dc.b $ED, $D, $0, $8, $0
	dc.b $FD, $8, $0, $10, $8
	dc.b $ED, $0, $0, $13, $F8
	dc.b $FD, $4, $0, $14, $F8
	dc.b $F5, $0, $0, $16, $F8
	dc.b $D5, $8, $0, $17, $E8
	dc.b $DD, $7, $0, $1A, $E8
	dc.b $E5, $3, $0, $22, $E0
	dc.b $FD, $4, $0, $26, $E8
	dc.b $5, $9, $0, $28, $E8
	dc.b $15, $4, $0, $2E, $E8
DATAHQKXO4QZ259_F: dc.b $7
	dc.b $F0, $7, $0, $0, $5
	dc.b $D0, $4, $0, $8, $ED
	dc.b $F8, $1, $0, $A, $15
	dc.b $0, $0, $0, $C, $FD
	dc.b $E0, $B, $0, $D, $ED
	dc.b $D8, $8, $0, $19, $ED
	dc.b $E8, $4, $0, $1C, $5
DATAHQKXO4QZ259_10: dc.b $D
	dc.b $DD, $9, $0, $0, $F8
	dc.b $DD, $1, $0, $6, $10
	dc.b $ED, $D, $0, $8, $0
	dc.b $FD, $8, $0, $10, $8
	dc.b $ED, $0, $0, $13, $F8
	dc.b $FD, $4, $0, $14, $F8
	dc.b $F5, $0, $0, $16, $F8
	dc.b $D5, $8, $0, $17, $E8
	dc.b $DD, $7, $0, $1A, $E8
	dc.b $E5, $3, $0, $22, $E0
	dc.b $FD, $4, $0, $26, $E8
	dc.b $5, $9, $0, $28, $E8
	dc.b $15, $4, $0, $2E, $E8
DATAHQKXO4QZ259_11: dc.b $7
	dc.b $F0, $7, $0, $0, $5
	dc.b $D0, $4, $0, $8, $ED
	dc.b $F8, $1, $0, $A, $15
	dc.b $0, $0, $0, $C, $FD
	dc.b $E0, $B, $0, $D, $ED
	dc.b $D8, $8, $0, $19, $ED
	dc.b $E8, $4, $0, $1C, $5
DATAHQKXO4QZ259_12: dc.b $C
	dc.b $E3, $9, $0, $0, $E8
	dc.b $FB, $4, $0, $6, $D8
	dc.b $F3, $9, $0, $8, $E8
	dc.b $E3, $6, $0, $E, $D8
	dc.b $EB, $1, $0, $14, $D0
	dc.b $3, $D, $0, $16, $D8
	dc.b $3, $5, $0, $1E, $F8
	dc.b $13, $C, $0, $22, $E0
	dc.b $13, $1, $0, $26, $0
	dc.b $1B, $4, $0, $28, $F0
	dc.b $EB, $5, $0, $2A, $0
	dc.b $E3, $0, $0, $2E, $8
DATAHQKXO4QZ259_13: dc.b $7
	dc.b $EC, $D, $0, $0, $D0
	dc.b $EC, $D, $0, $8, $F0
	dc.b $4, $0, $0, $10, $8
	dc.b $FC, $C, $0, $11, $E0
	dc.b $4, $4, $0, $15, $E8
	dc.b $FC, $4, $0, $17, $0
	dc.b $E4, $0, $0, $19, $8
DATAHQKXO4QZ259_14: dc.b $C
	dc.b $E3, $9, $0, $0, $E8
	dc.b $FB, $4, $0, $6, $D8
	dc.b $F3, $9, $0, $8, $E8
	dc.b $E3, $6, $0, $E, $D8
	dc.b $EB, $1, $0, $14, $D0
	dc.b $3, $D, $0, $16, $D8
	dc.b $3, $5, $0, $1E, $F8
	dc.b $13, $C, $0, $22, $E0
	dc.b $13, $1, $0, $26, $0
	dc.b $1B, $4, $0, $28, $F0
	dc.b $EB, $5, $0, $2A, $0
	dc.b $E3, $0, $0, $2E, $8
DATAHQKXO4QZ259_15: dc.b $7
	dc.b $EC, $D, $0, $0, $D0
	dc.b $EC, $D, $0, $8, $F0
	dc.b $4, $0, $0, $10, $8
	dc.b $FC, $C, $0, $11, $E0
	dc.b $4, $4, $0, $15, $E8
	dc.b $FC, $4, $0, $17, $0
	dc.b $E4, $0, $0, $19, $8
DATAHQKXO4QZ259_16: dc.b $C
	dc.b $E3, $9, $0, $0, $E8
	dc.b $FB, $4, $0, $6, $D8
	dc.b $F3, $9, $0, $8, $E8
	dc.b $E3, $6, $0, $E, $D8
	dc.b $EB, $1, $0, $14, $D0
	dc.b $3, $D, $0, $16, $D8
	dc.b $3, $5, $0, $1E, $F8
	dc.b $13, $C, $0, $22, $E0
	dc.b $13, $1, $0, $26, $0
	dc.b $1B, $4, $0, $28, $F0
	dc.b $EB, $5, $0, $2A, $0
	dc.b $E3, $0, $0, $2E, $8
DATAHQKXO4QZ259_17: dc.b $7
	dc.b $EC, $D, $0, $0, $D0
	dc.b $EC, $D, $0, $8, $F0
	dc.b $4, $0, $0, $10, $8
	dc.b $FC, $C, $0, $11, $E0
	dc.b $4, $4, $0, $15, $E8
	dc.b $FC, $4, $0, $17, $0
	dc.b $E4, $0, $0, $19, $8
DATAHQKXO4QZ259_18: dc.b $9
	dc.b $0, $7, $0, $0, $E5
	dc.b $0, $B, $0, $8, $F5
	dc.b $0, $2, $0, $14, $DD
	dc.b $0, $6, $0, $17, $D
	dc.b $8, $1, $0, $1D, $1D
	dc.b $F0, $D, $0, $1F, $E5
	dc.b $F8, $0, $0, $27, $5
	dc.b $E8, $0, $0, $28, $ED
	dc.b $E0, $9, $0, $29, $F5
DATAHQKXO4QZ259_19: dc.b $9
	dc.b $FD, $6, $0, $0, $DD
	dc.b $E5, $4, $0, $6, $FD
	dc.b $ED, $A, $0, $8, $ED
	dc.b $5, $4, $0, $11, $ED
	dc.b $D, $4, $0, $13, $ED
	dc.b $5, $1, $0, $15, $D5
	dc.b $ED, $5, $0, $17, $5
	dc.b $FD, $0, $0, $1B, $5
	dc.b $5, $1, $0, $1C, $FD
DATAHQKXO4QZ259_1A: dc.b $9
	dc.b $0, $7, $0, $0, $E5
	dc.b $0, $B, $0, $8, $F5
	dc.b $0, $2, $0, $14, $DD
	dc.b $0, $6, $0, $17, $D
	dc.b $8, $1, $0, $1D, $1D
	dc.b $F0, $D, $0, $1F, $E5
	dc.b $F8, $0, $0, $27, $5
	dc.b $E8, $0, $0, $28, $ED
	dc.b $E0, $9, $0, $29, $F5
DATAHQKXO4QZ259_1B: dc.b $9
	dc.b $FD, $6, $0, $0, $DD
	dc.b $E5, $4, $0, $6, $FD
	dc.b $ED, $A, $0, $8, $ED
	dc.b $5, $4, $0, $11, $ED
	dc.b $D, $4, $0, $13, $ED
	dc.b $5, $1, $0, $15, $D5
	dc.b $ED, $5, $0, $17, $5
	dc.b $FD, $0, $0, $1B, $5
	dc.b $5, $1, $0, $1C, $FD
DATAHQKXO4QZ259_1C: dc.b $9
	dc.b $0, $7, $0, $0, $E5
	dc.b $0, $B, $0, $8, $F5
	dc.b $0, $2, $0, $14, $DD
	dc.b $0, $6, $0, $17, $D
	dc.b $8, $1, $0, $1D, $1D
	dc.b $F0, $D, $0, $1F, $E5
	dc.b $F8, $0, $0, $27, $5
	dc.b $E8, $0, $0, $28, $ED
	dc.b $E0, $9, $0, $29, $F5
DATAHQKXO4QZ259_1D: dc.b $9
	dc.b $FD, $6, $0, $0, $DD
	dc.b $E5, $4, $0, $6, $FD
	dc.b $ED, $A, $0, $8, $ED
	dc.b $5, $4, $0, $11, $ED
	dc.b $D, $4, $0, $13, $ED
	dc.b $5, $1, $0, $15, $D5
	dc.b $ED, $5, $0, $17, $5
	dc.b $FD, $0, $0, $1B, $5
	dc.b $5, $1, $0, $1C, $FD
DATAHQKXO4QZ259_1E: dc.b $C
	dc.b $EE, $9, $0, $0, $10
	dc.b $FE, $E, $0, $6, $8
	dc.b $F6, $0, $0, $12, $8
	dc.b $F6, $3, $0, $13, $0
	dc.b $F6, $3, $0, $17, $F8
	dc.b $EE, $8, $0, $1B, $F8
	dc.b $E6, $8, $0, $1E, $F8
	dc.b $E6, $8, $0, $21, $10
	dc.b $DE, $4, $0, $24, $F
	dc.b $DE, $C, $0, $26, $E0
	dc.b $E6, $A, $0, $2A, $E0
	dc.b $FE, $5, $0, $33, $E0
DATAHQKXO4QZ259_1F: dc.b $B
	dc.b $FE, $E, $0, $0, $8
	dc.b $EE, $D, $0, $C, $8
	dc.b $E, $4, $0, $14, $F8
	dc.b $EE, $7, $0, $16, $F8
	dc.b $E6, $8, $0, $1E, $F8
	dc.b $E6, $8, $0, $21, $10
	dc.b $DE, $4, $0, $24, $10
	dc.b $DE, $C, $0, $26, $E0
	dc.b $E6, $A, $0, $2A, $E0
	dc.b $FE, $4, $0, $33, $E8
	dc.b $6, $0, $0, $35, $F0
DATAHQKXO4QZ259_20: dc.b $C
	dc.b $FE, $E, $0, $0, $10
	dc.b $EE, $9, $0, $C, $18
	dc.b $EE, $1, $0, $12, $10
	dc.b $EE, $7, $0, $14, $0
	dc.b $E, $4, $0, $1C, $0
	dc.b $DE, $4, $0, $1E, $10
	dc.b $E6, $8, $0, $20, $0
	dc.b $E6, $8, $0, $23, $18
	dc.b $DE, $F, $0, $26, $E0
	dc.b $FE, $C, $0, $36, $E0
	dc.b $E, $C, $0, $3A, $E0
	dc.b $6, $4, $0, $3E, $E0
DATAHQKXO4QZ259_21: dc.b $C
	dc.b $FE, $E, $0, $0, $10
	dc.b $F6, $C, $0, $C, $10
	dc.b $EE, $8, $0, $10, $18
	dc.b $EE, $0, $0, $13, $10
	dc.b $EE, $4, $0, $14, $0
	dc.b $F6, $7, $0, $16, $0
	dc.b $E6, $8, $0, $1E, $0
	dc.b $E6, $8, $0, $21, $18
	dc.b $E6, $C, $0, $24, $E0
	dc.b $EE, $F, $0, $28, $E0
	dc.b $E, $C, $0, $38, $E0
	dc.b $DE, $C, $0, $3C, $E0
DATAHQKXO4QZ259_22: dc.b $C
	dc.b $E0, $9, $0, $0, $FA
	dc.b $F8, $1, $0, $6, $FA
	dc.b $F0, $E, $0, $8, $2
	dc.b $F0, $0, $0, $14, $FA
	dc.b $8, $C, $0, $15, $FA
	dc.b $8, $0, $0, $19, $1A
	dc.b $10, $C, $0, $1A, $F2
	dc.b $F0, $3, $0, $1E, $F2
	dc.b $E8, $0, $0, $22, $F2
	dc.b $F0, $3, $0, $23, $EA
	dc.b $10, $1, $0, $27, $EA
	dc.b $F8, $B, $0, $29, $D2
DATAHQKXO4QZ259_23: dc.b $B
	dc.b $DB, $C, $0, $0, $FD
	dc.b $E3, $D, $0, $4, $5
	dc.b $E3, $5, $0, $C, $F5
	dc.b $F3, $D, $0, $10, $5
	dc.b $F3, $D, $0, $18, $E5
	dc.b $FB, $7, $0, $20, $D5
	dc.b $1B, $D, $0, $28, $E5
	dc.b $1B, $1, $0, $30, $5
	dc.b $13, $C, $0, $32, $E5
	dc.b $B, $C, $0, $36, $E5
	dc.b $3, $C, $0, $3A, $E5
DATAHQKXO4QZ259_24: dc.b $C
	dc.b $E0, $9, $0, $0, $FA
	dc.b $F8, $1, $0, $6, $FA
	dc.b $F0, $E, $0, $8, $2
	dc.b $F0, $0, $0, $14, $FA
	dc.b $8, $C, $0, $15, $FA
	dc.b $8, $0, $0, $19, $1A
	dc.b $10, $C, $0, $1A, $F2
	dc.b $F0, $3, $0, $1E, $F2
	dc.b $E8, $0, $0, $22, $F2
	dc.b $F0, $3, $0, $23, $EA
	dc.b $10, $1, $0, $27, $EA
	dc.b $F8, $B, $0, $29, $D2
DATAHQKXO4QZ259_25: dc.b $B
	dc.b $DB, $C, $0, $0, $FD
	dc.b $E3, $D, $0, $4, $5
	dc.b $E3, $5, $0, $C, $F5
	dc.b $F3, $D, $0, $10, $5
	dc.b $F3, $D, $0, $18, $E5
	dc.b $FB, $7, $0, $20, $D5
	dc.b $1B, $D, $0, $28, $E5
	dc.b $1B, $1, $0, $30, $5
	dc.b $13, $C, $0, $32, $E5
	dc.b $B, $C, $0, $36, $E5
	dc.b $3, $C, $0, $3A, $E5
DATAHQKXO4QZ259_26: dc.b $9
	dc.b $D8, $F, $0, $0, $E8
	dc.b $D8, $7, $0, $10, $8
	dc.b $F8, $D, $0, $18, $E8
	dc.b $F8, $5, $0, $20, $8
	dc.b $E0, $1, $0, $24, $E0
	dc.b $0, $0, $0, $26, $E0
	dc.b $8, $D, $0, $27, $E0
	dc.b $18, $C, $0, $2F, $E0
	dc.b $10, $5, $0, $33, $0
DATAHQKXO4QZ259_27: dc.b $C
	dc.b $0, $6, $0, $0, $E0
	dc.b $0, $B, $0, $6, $F0
	dc.b $D8, $C, $0, $12, $E8
	dc.b $18, $4, $0, $16, $E0
	dc.b $10, $5, $0, $18, $8
	dc.b $0, $1, $0, $1C, $10
	dc.b $F0, $D, $0, $1E, $E8
	dc.b $F0, $5, $0, $26, $8
	dc.b $E0, $D, $0, $2A, $E0
	dc.b $E0, $9, $0, $32, $0
	dc.b $D0, $5, $0, $38, $8
	dc.b $D0, $8, $0, $3C, $F0
DATAHQKXO4QZ259_28: dc.b $9
	dc.b $D8, $F, $0, $0, $E8
	dc.b $D8, $7, $0, $10, $8
	dc.b $F8, $D, $0, $18, $E8
	dc.b $F8, $5, $0, $20, $8
	dc.b $E0, $1, $0, $24, $E0
	dc.b $0, $0, $0, $26, $E0
	dc.b $8, $D, $0, $27, $E0
	dc.b $18, $C, $0, $2F, $E0
	dc.b $10, $5, $0, $33, $0
DATAHQKXO4QZ259_29: dc.b $C
	dc.b $0, $6, $0, $0, $E0
	dc.b $0, $B, $0, $6, $F0
	dc.b $D8, $C, $0, $12, $E8
	dc.b $18, $4, $0, $16, $E0
	dc.b $10, $5, $0, $18, $8
	dc.b $0, $1, $0, $1C, $10
	dc.b $F0, $D, $0, $1E, $E8
	dc.b $F0, $5, $0, $26, $8
	dc.b $E0, $D, $0, $2A, $E0
	dc.b $E0, $9, $0, $32, $0
	dc.b $D0, $5, $0, $38, $8
	dc.b $D0, $8, $0, $3C, $F0
DATAHQKXO4QZ259_2A: dc.b $9
	dc.b $D1, $D, $0, $0, $ED
	dc.b $9, $E, $0, $8, $F5
	dc.b $E1, $A, $0, $14, $DD
	dc.b $F9, $4, $0, $1D, $5
	dc.b $F9, $C, $0, $1F, $E5
	dc.b $1, $4, $0, $23, $ED
	dc.b $1, $C, $0, $25, $FD
	dc.b $E1, $E, $0, $29, $F5
	dc.b $9, $1, $0, $35, $15
DATAHQKXO4QZ259_2B: dc.b $8
	dc.b $F, $D, $0, $0, $F7
	dc.b $FF, $D, $0, $8, $EF
	dc.b $FF, $9, $0, $10, $F
	dc.b $E7, $E, $0, $16, $DF
	dc.b $E7, $E, $0, $22, $FF
	dc.b $D7, $3, $0, $2E, $D7
	dc.b $CF, $C, $0, $32, $DF
	dc.b $D7, $D, $0, $36, $DF
DATAHQKXO4QZ259_2C: dc.b $9
	dc.b $D1, $D, $0, $0, $ED
	dc.b $9, $E, $0, $8, $F5
	dc.b $E1, $A, $0, $14, $DD
	dc.b $F9, $4, $0, $1D, $5
	dc.b $F9, $C, $0, $1F, $E5
	dc.b $1, $4, $0, $23, $ED
	dc.b $1, $C, $0, $25, $FD
	dc.b $E1, $E, $0, $29, $F5
	dc.b $9, $1, $0, $35, $15
DATAHQKXO4QZ259_2D: dc.b $8
	dc.b $F, $D, $0, $0, $F7
	dc.b $FF, $D, $0, $8, $EF
	dc.b $FF, $9, $0, $10, $F
	dc.b $E7, $E, $0, $16, $DF
	dc.b $E7, $E, $0, $22, $FF
	dc.b $D7, $3, $0, $2E, $D7
	dc.b $CF, $C, $0, $32, $DF
	dc.b $D7, $D, $0, $36, $DF
DATAHQKXO4QZ259_2E: dc.b $4
	dc.b $F8, $F, $0, $0, $E8
	dc.b $F8, $7, $0, $10, $8
	dc.b $E8, $D, $0, $18, $E8
	dc.b $E8, $5, $0, $20, $8
DATAHQKXO4QZ259_2F: dc.b $4
	dc.b $F8, $F, $0, $0, $E8
	dc.b $F8, $7, $0, $10, $8
	dc.b $E8, $D, $0, $18, $E8
	dc.b $E8, $5, $0, $20, $8
DATAHQKXO4QZ259_30: dc.b $4
	dc.b $F8, $F, $0, $0, $E8
	dc.b $F8, $7, $0, $10, $8
	dc.b $E8, $D, $0, $18, $E8
	dc.b $E8, $5, $0, $20, $8
DATAHQKXO4QZ259_31: dc.b $4
	dc.b $F8, $F, $0, $0, $E8
	dc.b $F8, $7, $0, $10, $8
	dc.b $E8, $D, $0, $18, $E8
	dc.b $E8, $5, $0, $20, $8
DATAHQKXO4QZ259_32: dc.b $4
	dc.b $F8, $F, $0, $0, $E8
	dc.b $F8, $7, $0, $10, $8
	dc.b $E8, $D, $0, $18, $E8
	dc.b $E8, $5, $0, $20, $8
DATAHQKXO4QZ259_38: dc.b $9
	dc.b $F5, $9, $0, $0, $F8
	dc.b $5, $D, $0, $6, $F0
	dc.b $ED, $4, $0, $E, $F8
	dc.b $ED, $0, $0, $10, $8
	dc.b $E5, $C, $0, $11, $F0
	dc.b $CD, $E, $0, $15, $E8
	dc.b $CD, $B, $0, $21, $D0
	dc.b $ED, $8, $0, $2D, $D0
	dc.b $F5, $5, $0, $30, $D8
DATAHQKXO4QZ259_4C: dc.b $9
	dc.b $E0, $D, $0, $0, $F4
	dc.b $F0, $1, $0, $8, $C
	dc.b $F8, $9, $0, $A, $F4
	dc.b $10, $0, $0, $10, $F4
	dc.b $10, $0, $0, $11, $4
	dc.b $8, $8, $0, $12, $F4
	dc.b $F0, $8, $0, $15, $F4
	dc.b $F0, $5, $0, $18, $E4
	dc.b $F0, $4, $0, $1C, $14
DATAHQKXO4QZ259_55: dc.b $B
	dc.b $D8, $E, $0, $0, $DC
	dc.b $8, $1, $0, $C, $FC
	dc.b $F0, $C, $0, $E, $DC
	dc.b $F8, $E, $0, $12, $DC
	dc.b $10, $4, $0, $1E, $DC
	dc.b $F8, $4, $0, $20, $FC
	dc.b $D8, $3, $0, $22, $FC
	dc.b $D8, $2, $0, $26, $4
	dc.b $E0, $2, $0, $29, $C
	dc.b $E0, $3, $0, $2C, $14
	dc.b $10, $0, $0, $30, $F4
	even