; ================================================================================
; Sprite Mappings - generated by Flex 2 Wed Jul 11 2018 11:05:27 GMT-0700 (Pacific Daylight Time)
; ================================================================================

DATA9CNCSL68IDD:
	dc.w $0, DATA9CNCSL68IDD_1-DATA9CNCSL68IDD
	dc.w DATA9CNCSL68IDD_2-DATA9CNCSL68IDD, DATA9CNCSL68IDD_3-DATA9CNCSL68IDD
	dc.w DATA9CNCSL68IDD_4-DATA9CNCSL68IDD, DATA9CNCSL68IDD_5-DATA9CNCSL68IDD
	dc.w DATA9CNCSL68IDD_6-DATA9CNCSL68IDD, DATA9CNCSL68IDD_7-DATA9CNCSL68IDD
	dc.w DATA9CNCSL68IDD_8-DATA9CNCSL68IDD, DATA9CNCSL68IDD_9-DATA9CNCSL68IDD
	dc.w DATA9CNCSL68IDD_A-DATA9CNCSL68IDD, DATA9CNCSL68IDD_B-DATA9CNCSL68IDD
	dc.w DATA9CNCSL68IDD_C-DATA9CNCSL68IDD, DATA9CNCSL68IDD_D-DATA9CNCSL68IDD
	dc.w DATA9CNCSL68IDD_E-DATA9CNCSL68IDD, DATA9CNCSL68IDD_F-DATA9CNCSL68IDD
	dc.w DATA9CNCSL68IDD_10-DATA9CNCSL68IDD, DATA9CNCSL68IDD_11-DATA9CNCSL68IDD
	dc.w DATA9CNCSL68IDD_12-DATA9CNCSL68IDD, DATA9CNCSL68IDD_13-DATA9CNCSL68IDD
	dc.w DATA9CNCSL68IDD_14-DATA9CNCSL68IDD, DATA9CNCSL68IDD_15-DATA9CNCSL68IDD
	dc.w DATA9CNCSL68IDD_16-DATA9CNCSL68IDD, DATA9CNCSL68IDD_17-DATA9CNCSL68IDD
	dc.w DATA9CNCSL68IDD_18-DATA9CNCSL68IDD, DATA9CNCSL68IDD_19-DATA9CNCSL68IDD
	dc.w DATA9CNCSL68IDD_1A-DATA9CNCSL68IDD, DATA9CNCSL68IDD_1B-DATA9CNCSL68IDD
	dc.w DATA9CNCSL68IDD_1C-DATA9CNCSL68IDD, DATA9CNCSL68IDD_1D-DATA9CNCSL68IDD
	dc.w DATA9CNCSL68IDD_1E-DATA9CNCSL68IDD, DATA9CNCSL68IDD_1F-DATA9CNCSL68IDD
	dc.w DATA9CNCSL68IDD_20-DATA9CNCSL68IDD, DATA9CNCSL68IDD_21-DATA9CNCSL68IDD
	dc.w DATA9CNCSL68IDD_22-DATA9CNCSL68IDD, DATA9CNCSL68IDD_23-DATA9CNCSL68IDD
	dc.w DATA9CNCSL68IDD_24-DATA9CNCSL68IDD, DATA9CNCSL68IDD_25-DATA9CNCSL68IDD
	dc.w DATA9CNCSL68IDD_26-DATA9CNCSL68IDD, DATA9CNCSL68IDD_27-DATA9CNCSL68IDD
	dc.w DATA9CNCSL68IDD_28-DATA9CNCSL68IDD, DATA9CNCSL68IDD_29-DATA9CNCSL68IDD
	dc.w DATA9CNCSL68IDD_2A-DATA9CNCSL68IDD, DATA9CNCSL68IDD_2B-DATA9CNCSL68IDD
	dc.w DATA9CNCSL68IDD_2C-DATA9CNCSL68IDD, DATA9CNCSL68IDD_2D-DATA9CNCSL68IDD
	dc.w DATA9CNCSL68IDD_2E-DATA9CNCSL68IDD, DATA9CNCSL68IDD_2F-DATA9CNCSL68IDD
	dc.w DATA9CNCSL68IDD_30-DATA9CNCSL68IDD, DATA9CNCSL68IDD_31-DATA9CNCSL68IDD
	dc.w DATA9CNCSL68IDD_32-DATA9CNCSL68IDD, DATA9CNCSL68IDD_33-DATA9CNCSL68IDD
	dc.w DATA9CNCSL68IDD_34-DATA9CNCSL68IDD, DATA9CNCSL68IDD_35-DATA9CNCSL68IDD
	dc.w DATA9CNCSL68IDD_36-DATA9CNCSL68IDD, DATA9CNCSL68IDD_37-DATA9CNCSL68IDD
	dc.w DATA9CNCSL68IDD_38-DATA9CNCSL68IDD, DATA9CNCSL68IDD_39-DATA9CNCSL68IDD
	dc.w DATA9CNCSL68IDD_3A-DATA9CNCSL68IDD, DATA9CNCSL68IDD_3B-DATA9CNCSL68IDD
	dc.w DATA9CNCSL68IDD_3C-DATA9CNCSL68IDD, DATA9CNCSL68IDD_3D-DATA9CNCSL68IDD
	dc.w DATA9CNCSL68IDD_3E-DATA9CNCSL68IDD, DATA9CNCSL68IDD_3F-DATA9CNCSL68IDD
	dc.w DATA9CNCSL68IDD_40-DATA9CNCSL68IDD, DATA9CNCSL68IDD_41-DATA9CNCSL68IDD
	dc.w DATA9CNCSL68IDD_42-DATA9CNCSL68IDD, DATA9CNCSL68IDD_43-DATA9CNCSL68IDD
	dc.w DATA9CNCSL68IDD_44-DATA9CNCSL68IDD, DATA9CNCSL68IDD_45-DATA9CNCSL68IDD
	dc.w DATA9CNCSL68IDD_46-DATA9CNCSL68IDD, DATA9CNCSL68IDD_47-DATA9CNCSL68IDD
	dc.w DATA9CNCSL68IDD_48-DATA9CNCSL68IDD, DATA9CNCSL68IDD_49-DATA9CNCSL68IDD
	dc.w DATA9CNCSL68IDD_4A-DATA9CNCSL68IDD, DATA9CNCSL68IDD_4B-DATA9CNCSL68IDD
	dc.w DATA9CNCSL68IDD_4C-DATA9CNCSL68IDD, DATA9CNCSL68IDD_4D-DATA9CNCSL68IDD
	dc.w DATA9CNCSL68IDD_4E-DATA9CNCSL68IDD, DATA9CNCSL68IDD_4F-DATA9CNCSL68IDD
	dc.w DATA9CNCSL68IDD_50-DATA9CNCSL68IDD, DATA9CNCSL68IDD_51-DATA9CNCSL68IDD
	dc.w DATA9CNCSL68IDD_52-DATA9CNCSL68IDD, DATA9CNCSL68IDD_53-DATA9CNCSL68IDD
	dc.w DATA9CNCSL68IDD_54-DATA9CNCSL68IDD, DATA9CNCSL68IDD_55-DATA9CNCSL68IDD
	dc.w DATA9CNCSL68IDD_56-DATA9CNCSL68IDD, DATA9CNCSL68IDD_57-DATA9CNCSL68IDD
DATA9CNCSL68IDD_1: dc.b $7
	dc.b $EC, $8, $0, $0, $F0
	dc.b $F4, $D, $0, $3, $F0
	dc.b $4, $8, $0, $B, $F0
	dc.b $C, $8, $0, $E, $F8
	dc.b $EC, $0, $0, $11, $8
	dc.b $C, $0, $0, $12, $F0
	dc.b $4, $0, $0, $13, $8
DATA9CNCSL68IDD_2: dc.b $3
	dc.b $EC, $9, $0, $0, $F0
	dc.b $FC, $9, $0, $6, $F0
	dc.b $C, $8, $0, $C, $F8
DATA9CNCSL68IDD_3: dc.b $3
	dc.b $EC, $9, $0, $0, $F0
	dc.b $FC, $9, $0, $6, $F0
	dc.b $C, $8, $0, $C, $F8
DATA9CNCSL68IDD_4: dc.b $3
	dc.b $EC, $9, $0, $0, $F0
	dc.b $FC, $9, $0, $6, $F0
	dc.b $C, $8, $0, $C, $F8
DATA9CNCSL68IDD_5: dc.b $3
	dc.b $EC, $A, $0, $0, $F0
	dc.b $4, $8, $0, $9, $F0
	dc.b $C, $8, $0, $C, $F8
DATA9CNCSL68IDD_6: dc.b $3
	dc.b $EA, $C, $0, $0, $F0
	dc.b $F2, $F, $0, $4, $F0
	dc.b $F2, $3, $0, $14, $10
DATA9CNCSL68IDD_7: dc.b $2
	dc.b $FB, $E, $0, $0, $F1
	dc.b $EB, $D, $0, $C, $F1
DATA9CNCSL68IDD_8: dc.b $5
	dc.b $ED, $9, $0, $0, $F1
	dc.b $FD, $A, $0, $6, $F1
	dc.b $D, $0, $0, $F, $9
	dc.b $ED, $2, $0, $10, $9
	dc.b $5, $0, $0, $13, $9
DATA9CNCSL68IDD_9: dc.b $4
	dc.b $FC, $9, $0, $0, $F1
	dc.b $C, $C, $0, $6, $F1
	dc.b $EC, $3, $0, $A, $9
	dc.b $EC, $9, $0, $E, $F1
DATA9CNCSL68IDD_A: dc.b $4
	dc.b $FC, $E, $0, $0, $F1
	dc.b $EC, $1, $0, $C, $9
	dc.b $EC, $9, $0, $E, $F1
	dc.b $4, $1, $0, $14, $11
DATA9CNCSL68IDD_B: dc.b $6
	dc.b $FB, $C, $0, $0, $F1
	dc.b $3, $9, $0, $4, $1
	dc.b $EB, $D, $0, $A, $F1
	dc.b $3, $8, $0, $12, $E9
	dc.b $B, $0, $0, $15, $F9
	dc.b $B, $0, $0, $16, $F1
DATA9CNCSL68IDD_C: dc.b $5
	dc.b $E9, $9, $0, $0, $EC
	dc.b $E9, $1, $0, $6, $4
	dc.b $F9, $D, $0, $8, $F4
	dc.b $9, $8, $0, $10, $FC
	dc.b $F9, $0, $0, $13, $EC
DATA9CNCSL68IDD_D: dc.b $5
	dc.b $E9, $9, $0, $0, $EC
	dc.b $E9, $1, $0, $6, $4
	dc.b $F9, $D, $0, $8, $F4
	dc.b $9, $8, $0, $10, $FC
	dc.b $F9, $0, $0, $13, $EC
DATA9CNCSL68IDD_E: dc.b $5
	dc.b $E9, $9, $0, $0, $EC
	dc.b $E9, $1, $0, $6, $4
	dc.b $F9, $D, $0, $8, $F4
	dc.b $9, $8, $0, $10, $FC
	dc.b $F9, $0, $0, $13, $EC
DATA9CNCSL68IDD_F: dc.b $5
	dc.b $E9, $9, $0, $0, $EC
	dc.b $E9, $1, $0, $6, $4
	dc.b $F9, $D, $0, $8, $F4
	dc.b $9, $8, $0, $10, $FC
	dc.b $F9, $0, $0, $13, $EC
DATA9CNCSL68IDD_10: dc.b $5
	dc.b $E9, $9, $0, $0, $EC
	dc.b $E9, $1, $0, $6, $4
	dc.b $F9, $D, $0, $8, $F4
	dc.b $9, $8, $0, $10, $FC
	dc.b $F9, $0, $0, $13, $EC
DATA9CNCSL68IDD_11: dc.b $5
	dc.b $E9, $9, $0, $0, $EC
	dc.b $E9, $1, $0, $6, $4
	dc.b $F9, $D, $0, $8, $F4
	dc.b $9, $8, $0, $10, $FC
	dc.b $F9, $0, $0, $13, $EC
DATA9CNCSL68IDD_12: dc.b $4
	dc.b $F4, $9, $0, $0, $FB
	dc.b $C, $4, $0, $6, $EB
	dc.b $4, $9, $0, $8, $FB
	dc.b $F4, $6, $0, $E, $EB
DATA9CNCSL68IDD_13: dc.b $4
	dc.b $F4, $9, $0, $0, $FB
	dc.b $C, $4, $0, $6, $EB
	dc.b $4, $9, $0, $8, $FB
	dc.b $F4, $6, $0, $E, $EB
DATA9CNCSL68IDD_14: dc.b $4
	dc.b $F4, $9, $0, $0, $FB
	dc.b $C, $4, $0, $6, $EB
	dc.b $4, $9, $0, $8, $FB
	dc.b $F4, $6, $0, $E, $EB
DATA9CNCSL68IDD_15: dc.b $4
	dc.b $F4, $9, $0, $0, $FB
	dc.b $C, $4, $0, $6, $EB
	dc.b $4, $9, $0, $8, $FB
	dc.b $F4, $6, $0, $E, $EB
DATA9CNCSL68IDD_16: dc.b $4
	dc.b $F4, $9, $0, $0, $FB
	dc.b $C, $4, $0, $6, $EB
	dc.b $4, $9, $0, $8, $FB
	dc.b $F4, $6, $0, $E, $EB
DATA9CNCSL68IDD_17: dc.b $4
	dc.b $F4, $9, $0, $0, $FB
	dc.b $C, $4, $0, $6, $EB
	dc.b $4, $9, $0, $8, $FB
	dc.b $F4, $6, $0, $E, $EB
DATA9CNCSL68IDD_18: dc.b $5
	dc.b $FC, $6, $0, $0, $EC
	dc.b $F4, $4, $0, $6, $EC
	dc.b $EC, $A, $0, $8, $FC
	dc.b $4, $4, $0, $11, $FC
	dc.b $C, $4, $0, $13, $FC
DATA9CNCSL68IDD_19: dc.b $5
	dc.b $FC, $6, $0, $0, $EC
	dc.b $F4, $4, $0, $6, $EC
	dc.b $EC, $A, $0, $8, $FC
	dc.b $4, $4, $0, $11, $FC
	dc.b $C, $4, $0, $13, $FC
DATA9CNCSL68IDD_1A: dc.b $5
	dc.b $FC, $6, $0, $0, $EC
	dc.b $F4, $4, $0, $6, $EC
	dc.b $EC, $A, $0, $8, $FC
	dc.b $4, $4, $0, $11, $FC
	dc.b $C, $4, $0, $13, $FC
DATA9CNCSL68IDD_1B: dc.b $5
	dc.b $FC, $6, $0, $0, $EC
	dc.b $F4, $4, $0, $6, $EC
	dc.b $EC, $A, $0, $8, $FC
	dc.b $4, $4, $0, $11, $FC
	dc.b $C, $4, $0, $13, $FC
DATA9CNCSL68IDD_1C: dc.b $5
	dc.b $FC, $6, $0, $0, $EC
	dc.b $F4, $4, $0, $6, $EC
	dc.b $EC, $A, $0, $8, $FC
	dc.b $4, $4, $0, $11, $FC
	dc.b $C, $4, $0, $13, $FC
DATA9CNCSL68IDD_1D: dc.b $5
	dc.b $FC, $6, $0, $0, $EC
	dc.b $F4, $4, $0, $6, $EC
	dc.b $EC, $A, $0, $8, $FC
	dc.b $4, $4, $0, $11, $FC
	dc.b $C, $4, $0, $13, $FC
DATA9CNCSL68IDD_1E: dc.b $6
	dc.b $EE, $9, $0, $0, $FC
	dc.b $FE, $E, $0, $6, $F4
	dc.b $F6, $0, $0, $12, $F4
	dc.b $F6, $3, $0, $13, $EC
	dc.b $F6, $3, $0, $17, $E4
	dc.b $EE, $8, $0, $1B, $E4
DATA9CNCSL68IDD_1F: dc.b $4
	dc.b $FE, $E, $0, $0, $F4
	dc.b $EE, $D, $0, $C, $F4
	dc.b $E, $4, $0, $14, $E4
	dc.b $EE, $7, $0, $16, $E4
DATA9CNCSL68IDD_20: dc.b $5
	dc.b $FE, $E, $0, $0, $F4
	dc.b $EE, $9, $0, $C, $FC
	dc.b $EE, $1, $0, $12, $F4
	dc.b $EE, $7, $0, $14, $E4
	dc.b $E, $4, $0, $1C, $E4
DATA9CNCSL68IDD_21: dc.b $6
	dc.b $FE, $E, $0, $0, $F4
	dc.b $F6, $C, $0, $C, $F4
	dc.b $EE, $8, $0, $10, $FC
	dc.b $EE, $0, $0, $13, $F4
	dc.b $EE, $4, $0, $14, $E4
	dc.b $F6, $7, $0, $16, $E4
DATA9CNCSL68IDD_22: dc.b $4
	dc.b $EA, $9, $0, $0, $EE
	dc.b $EA, $1, $0, $6, $6
	dc.b $FA, $E, $0, $8, $F6
	dc.b $FA, $0, $0, $14, $EE
DATA9CNCSL68IDD_23: dc.b $4
	dc.b $EA, $9, $0, $0, $EE
	dc.b $EA, $1, $0, $6, $6
	dc.b $FA, $E, $0, $8, $F6
	dc.b $FA, $0, $0, $14, $EE
DATA9CNCSL68IDD_24: dc.b $4
	dc.b $EA, $9, $0, $0, $EE
	dc.b $EA, $1, $0, $6, $6
	dc.b $FA, $E, $0, $8, $F6
	dc.b $FA, $0, $0, $14, $EE
DATA9CNCSL68IDD_25: dc.b $4
	dc.b $EA, $9, $0, $0, $EE
	dc.b $EA, $1, $0, $6, $6
	dc.b $FA, $E, $0, $8, $F6
	dc.b $FA, $0, $0, $14, $EE
DATA9CNCSL68IDD_26: dc.b $4
	dc.b $EC, $6, $0, $0, $EE
	dc.b $EC, $B, $0, $6, $FE
	dc.b $4, $0, $0, $12, $F6
	dc.b $C, $C, $0, $13, $F6
DATA9CNCSL68IDD_27: dc.b $4
	dc.b $EC, $6, $0, $0, $EE
	dc.b $EC, $B, $0, $6, $FE
	dc.b $4, $0, $0, $12, $F6
	dc.b $C, $C, $0, $13, $F6
DATA9CNCSL68IDD_28: dc.b $4
	dc.b $EC, $6, $0, $0, $EE
	dc.b $EC, $B, $0, $6, $FE
	dc.b $4, $0, $0, $12, $F6
	dc.b $C, $C, $0, $13, $F6
DATA9CNCSL68IDD_29: dc.b $4
	dc.b $EC, $6, $0, $0, $EE
	dc.b $EC, $B, $0, $6, $FE
	dc.b $4, $0, $0, $12, $F6
	dc.b $C, $C, $0, $13, $F6
DATA9CNCSL68IDD_2A: dc.b $2
	dc.b $F2, $7, $0, $0, $EA
	dc.b $EA, $B, $0, $8, $FA
DATA9CNCSL68IDD_2B: dc.b $2
	dc.b $F2, $7, $0, $0, $EA
	dc.b $EA, $B, $0, $8, $FA
DATA9CNCSL68IDD_2C: dc.b $2
	dc.b $F2, $7, $0, $0, $EA
	dc.b $EA, $B, $0, $8, $FA
DATA9CNCSL68IDD_2D: dc.b $2
	dc.b $F2, $7, $0, $0, $EA
	dc.b $EA, $B, $0, $8, $FA
DATA9CNCSL68IDD_2E: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATA9CNCSL68IDD_2F: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATA9CNCSL68IDD_30: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATA9CNCSL68IDD_31: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATA9CNCSL68IDD_32: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATA9CNCSL68IDD_33: dc.b $2
	dc.b $F4, $E, $0, $0, $EC
	dc.b $F4, $2, $0, $C, $C
DATA9CNCSL68IDD_34: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATA9CNCSL68IDD_35: dc.b $2
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $8, $0, $C, $F4
DATA9CNCSL68IDD_36: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATA9CNCSL68IDD_37: dc.b $2
	dc.b $ED, $9, $0, $0, $F0
	dc.b $FD, $E, $0, $6, $F0
DATA9CNCSL68IDD_38: dc.b $4
	dc.b $ED, $9, $0, $0, $F0
	dc.b $FD, $D, $0, $6, $F0
	dc.b $D, $4, $0, $E, $0
	dc.b $5, $0, $0, $10, $E8
DATA9CNCSL68IDD_39: dc.b $4
	dc.b $F4, $4, $0, $0, $FC
	dc.b $FC, $D, $0, $2, $F4
	dc.b $C, $8, $0, $A, $F4
	dc.b $4, $0, $0, $D, $EC
DATA9CNCSL68IDD_3A: dc.b $3
	dc.b $EC, $8, $8, $0, $E8
	dc.b $F4, $2, $8, $3, $0
	dc.b $F4, $F, $8, $6, $E0
DATA9CNCSL68IDD_3B: dc.b $3
	dc.b $EC, $E, $8, $0, $E8
	dc.b $4, $D, $8, $C, $E0
	dc.b $C, $0, $18, $14, $0
DATA9CNCSL68IDD_3C: dc.b $3
	dc.b $F4, $D, $0, $0, $FC
	dc.b $FC, $5, $0, $8, $EC
	dc.b $4, $8, $0, $C, $FC
DATA9CNCSL68IDD_3D: dc.b $2
	dc.b $F4, $A, $0, $0, $E8
	dc.b $F4, $A, $8, $0, $0
DATA9CNCSL68IDD_3E: dc.b $3
	dc.b $F4, $D, $0, $0, $E4
	dc.b $FC, $0, $0, $8, $4
	dc.b $4, $C, $0, $9, $EC
DATA9CNCSL68IDD_3F: dc.b $3
	dc.b $F4, $D, $0, $0, $FC
	dc.b $FC, $5, $0, $8, $EC
	dc.b $4, $8, $0, $C, $FC
DATA9CNCSL68IDD_40: dc.b $3
	dc.b $E8, $B, $0, $0, $F0
	dc.b $8, $4, $0, $C, $F8
	dc.b $10, $0, $0, $E, $F8
DATA9CNCSL68IDD_41: dc.b $4
	dc.b $F8, $E, $0, $0, $E8
	dc.b $0, $5, $0, $C, $8
	dc.b $F8, $0, $0, $10, $8
	dc.b $F0, $0, $0, $11, $F8
DATA9CNCSL68IDD_42: dc.b $4
	dc.b $F8, $E, $0, $0, $E8
	dc.b $0, $5, $0, $C, $8
	dc.b $F8, $0, $0, $10, $8
	dc.b $F0, $0, $0, $11, $F8
DATA9CNCSL68IDD_43: dc.b $5
	dc.b $E8, $A, $0, $0, $F4
	dc.b $F0, $1, $0, $9, $C
	dc.b $0, $9, $0, $B, $F4
	dc.b $10, $4, $0, $11, $F4
	dc.b $0, $0, $0, $13, $EC
DATA9CNCSL68IDD_44: dc.b $5
	dc.b $E8, $A, $0, $0, $F4
	dc.b $E8, $1, $0, $9, $C
	dc.b $0, $9, $0, $B, $F4
	dc.b $10, $4, $0, $11, $F4
	dc.b $0, $0, $0, $13, $EC
DATA9CNCSL68IDD_45: dc.b $2
	dc.b $ED, $A, $0, $0, $F3
	dc.b $5, $D, $0, $9, $EB
DATA9CNCSL68IDD_46: dc.b $3
	dc.b $EC, $A, $0, $0, $F3
	dc.b $4, $8, $0, $9, $F3
	dc.b $C, $4, $0, $C, $F3
DATA9CNCSL68IDD_47: dc.b $2
	dc.b $ED, $A, $0, $0, $F3
	dc.b $5, $D, $0, $9, $EB
DATA9CNCSL68IDD_48: dc.b $3
	dc.b $EC, $A, $0, $0, $F3
	dc.b $4, $8, $0, $9, $F3
	dc.b $C, $4, $0, $C, $F3
DATA9CNCSL68IDD_49: dc.b $2
	dc.b $EC, $9, $0, $0, $F0
	dc.b $FC, $E, $0, $6, $F0
DATA9CNCSL68IDD_4A: dc.b $3
	dc.b $EC, $A, $0, $0, $F0
	dc.b $4, $5, $0, $9, $F8
	dc.b $E4, $0, $0, $D, $F8
DATA9CNCSL68IDD_4B: dc.b $3
	dc.b $E8, $D, $0, $0, $EC
	dc.b $E8, $1, $0, $8, $C
	dc.b $F8, $B, $0, $A, $F4
DATA9CNCSL68IDD_4C: dc.b $5
	dc.b $E8, $D, $0, $0, $EC
	dc.b $E8, $1, $0, $8, $C
	dc.b $F8, $9, $0, $A, $F4
	dc.b $8, $C, $0, $10, $F4
	dc.b $10, $0, $0, $14, $F4
DATA9CNCSL68IDD_4D: dc.b $5
	dc.b $E8, $D, $0, $0, $EC
	dc.b $E8, $1, $0, $8, $C
	dc.b $F8, $9, $0, $A, $F4
	dc.b $8, $C, $0, $10, $F4
	dc.b $10, $0, $0, $14, $F4
DATA9CNCSL68IDD_4E: dc.b $2
	dc.b $EC, $8, $0, $0, $F0
	dc.b $F4, $F, $0, $3, $F0
DATA9CNCSL68IDD_4F: dc.b $3
	dc.b $EC, $8, $0, $0, $F0
	dc.b $F4, $E, $0, $3, $F0
	dc.b $C, $8, $0, $F, $F8
DATA9CNCSL68IDD_50: dc.b $1
	dc.b $F0, $B, $0, $0, $F4
DATA9CNCSL68IDD_51: dc.b $1
	dc.b $F4, $6, $0, $0, $F8
DATA9CNCSL68IDD_52: dc.b $1
	dc.b $F8, $1, $0, $0, $FC
DATA9CNCSL68IDD_53: dc.b $3
	dc.b $F4, $D, $8, $0, $E4
	dc.b $FC, $5, $8, $8, $4
	dc.b $4, $8, $8, $C, $EC
DATA9CNCSL68IDD_54: dc.b $3
	dc.b $F4, $D, $8, $0, $FC
	dc.b $FC, $0, $8, $8, $F4
	dc.b $4, $C, $8, $9, $F4
DATA9CNCSL68IDD_55: dc.b $3
	dc.b $F0, $E, $0, $0, $EC
	dc.b $F8, $1, $0, $C, $C
	dc.b $8, $C, $0, $E, $F4
DATA9CNCSL68IDD_56: dc.b $3
	dc.b $EB, $9, $0, $0, $F4
	dc.b $FB, $E, $0, $6, $EC
	dc.b $3, $1, $0, $12, $C
DATA9CNCSL68IDD_57: dc.b $2
	dc.b $F0, $F, $0, $0, $EC
	dc.b $F8, $2, $0, $10, $C
	even