; ================================================================================
; Sprite Mappings - generated by Flex 2 Sat Jun 23 2018 14:02:35 GMT-0700 (Pacific Daylight Time)
; ================================================================================

DATAE84JSC6H85R:
	dc.w $0, DATAE84JSC6H85R_1-DATAE84JSC6H85R
	dc.w DATAE84JSC6H85R_2-DATAE84JSC6H85R, DATAE84JSC6H85R_3-DATAE84JSC6H85R
	dc.w DATAE84JSC6H85R_4-DATAE84JSC6H85R, DATAE84JSC6H85R_5-DATAE84JSC6H85R
	dc.w DATAE84JSC6H85R_6-DATAE84JSC6H85R, DATAE84JSC6H85R_7-DATAE84JSC6H85R
	dc.w DATAE84JSC6H85R_8-DATAE84JSC6H85R, DATAE84JSC6H85R_9-DATAE84JSC6H85R
	dc.w DATAE84JSC6H85R_A-DATAE84JSC6H85R, DATAE84JSC6H85R_B-DATAE84JSC6H85R
	dc.w DATAE84JSC6H85R_C-DATAE84JSC6H85R, DATAE84JSC6H85R_D-DATAE84JSC6H85R
	dc.w DATAE84JSC6H85R_E-DATAE84JSC6H85R, DATAE84JSC6H85R_F-DATAE84JSC6H85R
	dc.w DATAE84JSC6H85R_10-DATAE84JSC6H85R, DATAE84JSC6H85R_11-DATAE84JSC6H85R
	dc.w DATAE84JSC6H85R_12-DATAE84JSC6H85R, DATAE84JSC6H85R_13-DATAE84JSC6H85R
	dc.w DATAE84JSC6H85R_14-DATAE84JSC6H85R, DATAE84JSC6H85R_15-DATAE84JSC6H85R
	dc.w DATAE84JSC6H85R_16-DATAE84JSC6H85R, DATAE84JSC6H85R_17-DATAE84JSC6H85R
	dc.w DATAE84JSC6H85R_18-DATAE84JSC6H85R, DATAE84JSC6H85R_19-DATAE84JSC6H85R
	dc.w DATAE84JSC6H85R_1A-DATAE84JSC6H85R, DATAE84JSC6H85R_1B-DATAE84JSC6H85R
	dc.w DATAE84JSC6H85R_1C-DATAE84JSC6H85R, DATAE84JSC6H85R_1D-DATAE84JSC6H85R
	dc.w DATAE84JSC6H85R_1E-DATAE84JSC6H85R, DATAE84JSC6H85R_1F-DATAE84JSC6H85R
	dc.w DATAE84JSC6H85R_20-DATAE84JSC6H85R, DATAE84JSC6H85R_21-DATAE84JSC6H85R
	dc.w DATAE84JSC6H85R_22-DATAE84JSC6H85R, DATAE84JSC6H85R_23-DATAE84JSC6H85R
	dc.w DATAE84JSC6H85R_24-DATAE84JSC6H85R, DATAE84JSC6H85R_25-DATAE84JSC6H85R
	dc.w DATAE84JSC6H85R_26-DATAE84JSC6H85R, DATAE84JSC6H85R_27-DATAE84JSC6H85R
	dc.w DATAE84JSC6H85R_28-DATAE84JSC6H85R, DATAE84JSC6H85R_29-DATAE84JSC6H85R
	dc.w DATAE84JSC6H85R_2A-DATAE84JSC6H85R, DATAE84JSC6H85R_2B-DATAE84JSC6H85R
	dc.w DATAE84JSC6H85R_2C-DATAE84JSC6H85R, DATAE84JSC6H85R_2D-DATAE84JSC6H85R
	dc.w DATAE84JSC6H85R_2E-DATAE84JSC6H85R, DATAE84JSC6H85R_2F-DATAE84JSC6H85R
	dc.w DATAE84JSC6H85R_30-DATAE84JSC6H85R, DATAE84JSC6H85R_31-DATAE84JSC6H85R
	dc.w DATAE84JSC6H85R_32-DATAE84JSC6H85R, DATAE84JSC6H85R_33-DATAE84JSC6H85R
	dc.w DATAE84JSC6H85R_34-DATAE84JSC6H85R, DATAE84JSC6H85R_35-DATAE84JSC6H85R
	dc.w DATAE84JSC6H85R_36-DATAE84JSC6H85R, DATAE84JSC6H85R_37-DATAE84JSC6H85R
	dc.w DATAE84JSC6H85R_38-DATAE84JSC6H85R, DATAE84JSC6H85R_39-DATAE84JSC6H85R
	dc.w DATAE84JSC6H85R_3A-DATAE84JSC6H85R, DATAE84JSC6H85R_3B-DATAE84JSC6H85R
	dc.w DATAE84JSC6H85R_3C-DATAE84JSC6H85R, DATAE84JSC6H85R_3D-DATAE84JSC6H85R
	dc.w DATAE84JSC6H85R_3E-DATAE84JSC6H85R, DATAE84JSC6H85R_3F-DATAE84JSC6H85R
	dc.w DATAE84JSC6H85R_40-DATAE84JSC6H85R, DATAE84JSC6H85R_41-DATAE84JSC6H85R
	dc.w DATAE84JSC6H85R_42-DATAE84JSC6H85R, DATAE84JSC6H85R_43-DATAE84JSC6H85R
	dc.w DATAE84JSC6H85R_44-DATAE84JSC6H85R, DATAE84JSC6H85R_45-DATAE84JSC6H85R
	dc.w DATAE84JSC6H85R_46-DATAE84JSC6H85R, DATAE84JSC6H85R_47-DATAE84JSC6H85R
	dc.w DATAE84JSC6H85R_48-DATAE84JSC6H85R, DATAE84JSC6H85R_49-DATAE84JSC6H85R
	dc.w DATAE84JSC6H85R_4A-DATAE84JSC6H85R, DATAE84JSC6H85R_4B-DATAE84JSC6H85R
	dc.w DATAE84JSC6H85R_4C-DATAE84JSC6H85R, DATAE84JSC6H85R_4D-DATAE84JSC6H85R
	dc.w DATAE84JSC6H85R_4E-DATAE84JSC6H85R, DATAE84JSC6H85R_4F-DATAE84JSC6H85R
	dc.w DATAE84JSC6H85R_50-DATAE84JSC6H85R, DATAE84JSC6H85R_51-DATAE84JSC6H85R
	dc.w DATAE84JSC6H85R_52-DATAE84JSC6H85R, DATAE84JSC6H85R_53-DATAE84JSC6H85R
	dc.w DATAE84JSC6H85R_54-DATAE84JSC6H85R, DATAE84JSC6H85R_55-DATAE84JSC6H85R
	dc.w DATAE84JSC6H85R_56-DATAE84JSC6H85R, DATAE84JSC6H85R_57-DATAE84JSC6H85R
DATAE84JSC6H85R_1: dc.b $7
	dc.b $EC, $8, $0, $0, $F0
	dc.b $F4, $D, $0, $3, $F0
	dc.b $4, $8, $0, $B, $F0
	dc.b $C, $8, $0, $E, $F8
	dc.b $EC, $0, $0, $11, $8
	dc.b $C, $0, $0, $12, $F0
	dc.b $4, $0, $0, $13, $8
DATAE84JSC6H85R_2: dc.b $3
	dc.b $EC, $9, $0, $0, $F0
	dc.b $FC, $9, $0, $6, $F0
	dc.b $C, $8, $0, $C, $F8
DATAE84JSC6H85R_3: dc.b $3
	dc.b $EC, $9, $0, $0, $F0
	dc.b $FC, $9, $0, $6, $F0
	dc.b $C, $8, $0, $C, $F8
DATAE84JSC6H85R_4: dc.b $3
	dc.b $EC, $9, $0, $0, $F0
	dc.b $FC, $9, $0, $6, $F0
	dc.b $C, $8, $0, $C, $F8
DATAE84JSC6H85R_5: dc.b $3
	dc.b $EC, $A, $0, $0, $F0
	dc.b $4, $8, $0, $9, $F0
	dc.b $C, $8, $0, $C, $F8
DATAE84JSC6H85R_6: dc.b $4
	dc.b $EA, $C, $0, $0, $F0
	dc.b $F2, $F, $0, $4, $F0
	dc.b $F2, $3, $0, $14, $10
	dc.b $A, $0, $0, $18, $E8
DATAE84JSC6H85R_7: dc.b $2
	dc.b $FB, $E, $0, $0, $F1
	dc.b $EB, $D, $0, $C, $F1
DATAE84JSC6H85R_8: dc.b $4
	dc.b $ED, $9, $0, $0, $F1
	dc.b $FD, $A, $0, $6, $F1
	dc.b $D, $0, $0, $F, $9
	dc.b $ED, $2, $0, $10, $9
DATAE84JSC6H85R_9: dc.b $4
	dc.b $FC, $9, $0, $0, $F1
	dc.b $C, $C, $0, $6, $F1
	dc.b $EC, $3, $0, $A, $9
	dc.b $EC, $9, $0, $E, $F1
DATAE84JSC6H85R_A: dc.b $4
	dc.b $FC, $E, $0, $0, $F1
	dc.b $EC, $1, $0, $C, $9
	dc.b $EC, $9, $0, $E, $F1
	dc.b $4, $1, $0, $14, $11
DATAE84JSC6H85R_B: dc.b $6
	dc.b $FB, $C, $0, $0, $F1
	dc.b $3, $9, $0, $4, $1
	dc.b $EB, $D, $0, $A, $F1
	dc.b $3, $8, $0, $12, $E9
	dc.b $B, $0, $0, $15, $E9
	dc.b $FB, $0, $0, $16, $11
DATAE84JSC6H85R_C: dc.b $8
	dc.b $E3, $9, $0, $0, $EB
	dc.b $E3, $6, $0, $6, $3
	dc.b $F3, $8, $0, $C, $EB
	dc.b $FB, $9, $0, $F, $EB
	dc.b $FB, $0, $0, $15, $3
	dc.b $B, $1, $0, $16, $F3
	dc.b $B, $1, $0, $18, $FB
	dc.b $FB, $0, $0, $1A, $B
DATAE84JSC6H85R_D: dc.b $5
	dc.b $FB, $C, $0, $0, $EB
	dc.b $3, $9, $0, $4, $F3
	dc.b $E3, $E, $0, $A, $EB
	dc.b $F3, $1, $0, $16, $B
	dc.b $3, $0, $0, $18, $B
DATAE84JSC6H85R_E: dc.b $5
	dc.b $E9, $9, $0, $0, $EC
	dc.b $E9, $1, $0, $6, $4
	dc.b $F9, $D, $0, $8, $F4
	dc.b $9, $8, $0, $10, $FC
	dc.b $F9, $0, $0, $13, $EC
DATAE84JSC6H85R_F: dc.b $5
	dc.b $EA, $9, $0, $0, $EC
	dc.b $FA, $D, $0, $6, $EC
	dc.b $A, $8, $0, $E, $FC
	dc.b $EA, $1, $0, $11, $4
	dc.b $FA, $1, $0, $13, $C
DATAE84JSC6H85R_10: dc.b $7
	dc.b $E8, $1, $0, $0, $4
	dc.b $F8, $D, $0, $2, $F4
	dc.b $8, $8, $0, $A, $FC
	dc.b $E8, $D, $0, $D, $E4
	dc.b $F8, $4, $0, $15, $E4
	dc.b $8, $0, $0, $17, $F4
	dc.b $10, $C, $0, $18, $F4
DATAE84JSC6H85R_11: dc.b $7
	dc.b $EA, $1, $0, $0, $FF
	dc.b $FA, $D, $0, $2, $EF
	dc.b $A, $8, $0, $A, $F7
	dc.b $EA, $9, $0, $D, $E7
	dc.b $F2, $4, $0, $13, $7
	dc.b $FA, $1, $0, $15, $F
	dc.b $12, $0, $0, $17, $F7
DATAE84JSC6H85R_12: dc.b $6
	dc.b $F4, $7, $0, $0, $EB
	dc.b $EC, $9, $0, $8, $FB
	dc.b $FC, $4, $0, $E, $FB
	dc.b $4, $9, $0, $10, $FB
	dc.b $FC, $0, $0, $16, $B
	dc.b $14, $0, $0, $17, $B
DATAE84JSC6H85R_13: dc.b $2
	dc.b $F4, $7, $0, $0, $EB
	dc.b $F4, $B, $0, $8, $FB
DATAE84JSC6H85R_14: dc.b $4
	dc.b $FB, $A, $0, $0, $FB
	dc.b $F3, $7, $0, $9, $EB
	dc.b $F3, $0, $0, $11, $FB
	dc.b $F3, $0, $0, $12, $B
DATAE84JSC6H85R_15: dc.b $4
	dc.b $F4, $9, $0, $0, $FB
	dc.b $C, $4, $0, $6, $EB
	dc.b $4, $9, $0, $8, $FB
	dc.b $F4, $6, $0, $E, $EB
DATAE84JSC6H85R_16: dc.b $3
	dc.b $F4, $B, $0, $0, $FB
	dc.b $F4, $7, $0, $C, $EB
	dc.b $EC, $4, $0, $14, $3
DATAE84JSC6H85R_17: dc.b $7
	dc.b $F, $0, $0, $0, $B
	dc.b $F7, $3, $0, $1, $3
	dc.b $EF, $3, $0, $5, $FB
	dc.b $E7, $8, $0, $9, $FB
	dc.b $EF, $4, $0, $C, $3
	dc.b $F7, $0, $0, $E, $B
	dc.b $EF, $7, $0, $F, $EB
DATAE84JSC6H85R_18: dc.b $9
	dc.b $FC, $6, $0, $0, $E3
	dc.b $EC, $4, $0, $6, $E3
	dc.b $F4, $4, $0, $8, $E3
	dc.b $F4, $A, $0, $A, $F3
	dc.b $C, $0, $0, $13, $F3
	dc.b $C, $0, $0, $14, $FB
	dc.b $EC, $4, $0, $15, $F3
	dc.b $C, $0, $0, $17, $3
	dc.b $FC, $5, $0, $18, $B
DATAE84JSC6H85R_19: dc.b $6
	dc.b $FB, $8, $0, $0, $0
	dc.b $EB, $4, $0, $3, $F8
	dc.b $3, $4, $0, $5, $0
	dc.b $F3, $A, $0, $7, $E8
	dc.b $B, $C, $0, $10, $E8
	dc.b $F3, $0, $0, $14, $0
DATAE84JSC6H85R_1A: dc.b $5
	dc.b $FC, $6, $0, $0, $EC
	dc.b $F4, $4, $0, $6, $EC
	dc.b $EC, $A, $0, $8, $FC
	dc.b $4, $4, $0, $11, $FC
	dc.b $C, $4, $0, $13, $FC
DATAE84JSC6H85R_1B: dc.b $5
	dc.b $FB, $6, $0, $0, $EC
	dc.b $B, $4, $0, $6, $FC
	dc.b $3, $4, $0, $8, $FC
	dc.b $EB, $A, $0, $A, $FC
	dc.b $F3, $4, $0, $13, $EC
DATAE84JSC6H85R_1C: dc.b $9
	dc.b $EF, $4, $0, $0, $E9
	dc.b $E7, $A, $0, $2, $F9
	dc.b $FF, $4, $0, $B, $F9
	dc.b $F7, $1, $0, $D, $11
	dc.b $FF, $0, $0, $F, $9
	dc.b $F7, $3, $0, $10, $E9
	dc.b $F7, $3, $0, $14, $F1
	dc.b $7, $5, $0, $18, $F8
	dc.b $7, $0, $0, $1C, $8
DATAE84JSC6H85R_1D: dc.b $7
	dc.b $FE, $A, $0, $0, $EA
	dc.b $6, $4, $0, $9, $2
	dc.b $FE, $8, $0, $B, $2
	dc.b $F6, $8, $0, $E, $EA
	dc.b $F6, $0, $0, $11, $2
	dc.b $EE, $8, $0, $12, $F2
	dc.b $E6, $8, $0, $15, $F2
DATAE84JSC6H85R_1E: dc.b $3
	dc.b $EE, $9, $0, $0, $FC
	dc.b $FE, $E, $0, $6, $F4
	dc.b $F6, $0, $0, $12, $F4
DATAE84JSC6H85R_1F: dc.b $2
	dc.b $FE, $E, $0, $0, $F4
	dc.b $EE, $D, $0, $C, $F4
DATAE84JSC6H85R_20: dc.b $2
	dc.b $FE, $E, $0, $0, $F4
	dc.b $EE, $9, $0, $C, $FC
DATAE84JSC6H85R_21: dc.b $3
	dc.b $FE, $E, $0, $0, $F4
	dc.b $F6, $C, $0, $C, $F4
	dc.b $EE, $8, $0, $10, $FC
DATAE84JSC6H85R_22: dc.b $4
	dc.b $EA, $9, $0, $0, $EE
	dc.b $EA, $1, $0, $6, $6
	dc.b $FA, $E, $0, $8, $F6
	dc.b $FA, $0, $0, $14, $EE
DATAE84JSC6H85R_23: dc.b $3
	dc.b $EA, $9, $0, $0, $EE
	dc.b $EA, $1, $0, $6, $6
	dc.b $FA, $E, $0, $8, $F6
DATAE84JSC6H85R_24: dc.b $3
	dc.b $FA, $E, $0, $0, $F4
	dc.b $EA, $D, $0, $C, $EC
	dc.b $FA, $0, $0, $14, $EC
DATAE84JSC6H85R_25: dc.b $2
	dc.b $F9, $E, $0, $0, $F5
	dc.b $E9, $D, $0, $C, $EC
DATAE84JSC6H85R_26: dc.b $3
	dc.b $EC, $6, $0, $0, $EE
	dc.b $EC, $B, $0, $6, $FE
	dc.b $4, $0, $0, $12, $F6
DATAE84JSC6H85R_27: dc.b $3
	dc.b $EC, $6, $0, $0, $EE
	dc.b $EC, $B, $0, $6, $FE
	dc.b $4, $4, $0, $12, $EE
DATAE84JSC6H85R_28: dc.b $2
	dc.b $EC, $B, $0, $0, $FE
	dc.b $EC, $6, $0, $C, $EE
DATAE84JSC6H85R_29: dc.b $3
	dc.b $EC, $B, $0, $0, $FE
	dc.b $4, $0, $0, $C, $F6
	dc.b $EC, $6, $0, $D, $EE
DATAE84JSC6H85R_2A: dc.b $4
	dc.b $FA, $6, $0, $0, $EA
	dc.b $F2, $4, $0, $6, $EA
	dc.b $EA, $B, $0, $8, $FA
	dc.b $A, $0, $0, $14, $FA
DATAE84JSC6H85R_2B: dc.b $2
	dc.b $F2, $7, $0, $0, $EA
	dc.b $EA, $B, $0, $8, $FA
DATAE84JSC6H85R_2C: dc.b $3
	dc.b $EC, $B, $0, $0, $FA
	dc.b $F4, $7, $0, $C, $EA
	dc.b $C, $0, $0, $14, $FA
DATAE84JSC6H85R_2D: dc.b $2
	dc.b $EC, $B, $0, $0, $FA
	dc.b $F4, $7, $0, $C, $EA
DATAE84JSC6H85R_2E: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAE84JSC6H85R_2F: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAE84JSC6H85R_30: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAE84JSC6H85R_31: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAE84JSC6H85R_32: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAE84JSC6H85R_33: dc.b $2
	dc.b $F4, $E, $0, $0, $EC
	dc.b $F4, $2, $0, $C, $C
DATAE84JSC6H85R_34: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAE84JSC6H85R_35: dc.b $2
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $8, $0, $C, $F4
DATAE84JSC6H85R_36: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAE84JSC6H85R_37: dc.b $2
	dc.b $ED, $9, $0, $0, $F0
	dc.b $FD, $E, $0, $6, $F0
DATAE84JSC6H85R_38: dc.b $4
	dc.b $ED, $9, $0, $0, $F0
	dc.b $FD, $D, $0, $6, $F0
	dc.b $D, $4, $0, $E, $0
	dc.b $5, $0, $0, $10, $E8
DATAE84JSC6H85R_39: dc.b $4
	dc.b $F4, $4, $0, $0, $FC
	dc.b $FC, $D, $0, $2, $F4
	dc.b $C, $8, $0, $A, $F4
	dc.b $4, $0, $0, $D, $EC
DATAE84JSC6H85R_3A: dc.b $3
	dc.b $EC, $8, $8, $0, $E8
	dc.b $F4, $2, $8, $3, $0
	dc.b $F4, $F, $8, $6, $E0
DATAE84JSC6H85R_3B: dc.b $3
	dc.b $EC, $E, $8, $0, $E8
	dc.b $4, $D, $8, $C, $E0
	dc.b $C, $0, $18, $14, $0
DATAE84JSC6H85R_3C: dc.b $3
	dc.b $F4, $D, $0, $0, $FC
	dc.b $FC, $5, $0, $8, $EC
	dc.b $4, $8, $0, $C, $FC
DATAE84JSC6H85R_3D: dc.b $2
	dc.b $F4, $A, $0, $0, $E8
	dc.b $F4, $A, $8, $0, $0
DATAE84JSC6H85R_3E: dc.b $3
	dc.b $F4, $D, $0, $0, $E4
	dc.b $FC, $0, $0, $8, $4
	dc.b $4, $C, $0, $9, $EC
DATAE84JSC6H85R_3F: dc.b $3
	dc.b $F4, $D, $0, $0, $FC
	dc.b $FC, $5, $0, $8, $EC
	dc.b $4, $8, $0, $C, $FC
DATAE84JSC6H85R_40: dc.b $3
	dc.b $E8, $B, $0, $0, $F0
	dc.b $8, $4, $0, $C, $F8
	dc.b $10, $0, $0, $E, $F8
DATAE84JSC6H85R_41: dc.b $4
	dc.b $F8, $E, $0, $0, $E8
	dc.b $0, $5, $0, $C, $8
	dc.b $F8, $0, $0, $10, $8
	dc.b $F0, $0, $0, $11, $F8
DATAE84JSC6H85R_42: dc.b $4
	dc.b $F8, $E, $0, $0, $E8
	dc.b $0, $5, $0, $C, $8
	dc.b $F8, $0, $0, $10, $8
	dc.b $F0, $0, $0, $11, $F8
DATAE84JSC6H85R_43: dc.b $5
	dc.b $E8, $A, $0, $0, $F4
	dc.b $F0, $1, $0, $9, $C
	dc.b $0, $9, $0, $B, $F4
	dc.b $10, $4, $0, $11, $F4
	dc.b $0, $0, $0, $13, $EC
DATAE84JSC6H85R_44: dc.b $5
	dc.b $E8, $A, $0, $0, $F4
	dc.b $E8, $1, $0, $9, $C
	dc.b $0, $9, $0, $B, $F4
	dc.b $10, $4, $0, $11, $F4
	dc.b $0, $0, $0, $13, $EC
DATAE84JSC6H85R_45: dc.b $2
	dc.b $ED, $A, $0, $0, $F3
	dc.b $5, $D, $0, $9, $EB
DATAE84JSC6H85R_46: dc.b $3
	dc.b $EC, $A, $0, $0, $F3
	dc.b $4, $8, $0, $9, $F3
	dc.b $C, $4, $0, $C, $F3
DATAE84JSC6H85R_47: dc.b $2
	dc.b $ED, $A, $0, $0, $F3
	dc.b $5, $D, $0, $9, $EB
DATAE84JSC6H85R_48: dc.b $3
	dc.b $EC, $A, $0, $0, $F3
	dc.b $4, $8, $0, $9, $F3
	dc.b $C, $4, $0, $C, $F3
DATAE84JSC6H85R_49: dc.b $2
	dc.b $EC, $9, $0, $0, $F0
	dc.b $FC, $E, $0, $6, $F0
DATAE84JSC6H85R_4A: dc.b $3
	dc.b $EC, $A, $0, $0, $F0
	dc.b $4, $5, $0, $9, $F8
	dc.b $E4, $0, $0, $D, $F8
DATAE84JSC6H85R_4B: dc.b $3
	dc.b $E8, $D, $0, $0, $EC
	dc.b $E8, $1, $0, $8, $C
	dc.b $F8, $B, $0, $A, $F4
DATAE84JSC6H85R_4C: dc.b $5
	dc.b $E8, $D, $0, $0, $EC
	dc.b $E8, $1, $0, $8, $C
	dc.b $F8, $9, $0, $A, $F4
	dc.b $8, $C, $0, $10, $F4
	dc.b $10, $0, $0, $14, $F4
DATAE84JSC6H85R_4D: dc.b $5
	dc.b $E8, $D, $0, $0, $EC
	dc.b $E8, $1, $0, $8, $C
	dc.b $F8, $9, $0, $A, $F4
	dc.b $8, $C, $0, $10, $F4
	dc.b $10, $0, $0, $14, $F4
DATAE84JSC6H85R_4E: dc.b $2
	dc.b $EC, $8, $0, $0, $F0
	dc.b $F4, $F, $0, $3, $F0
DATAE84JSC6H85R_4F: dc.b $3
	dc.b $EC, $8, $0, $0, $F0
	dc.b $F4, $E, $0, $3, $F0
	dc.b $C, $8, $0, $F, $F8
DATAE84JSC6H85R_50: dc.b $1
	dc.b $F0, $B, $0, $0, $F4
DATAE84JSC6H85R_51: dc.b $1
	dc.b $F4, $6, $0, $0, $F8
DATAE84JSC6H85R_52: dc.b $1
	dc.b $F8, $1, $0, $0, $FC
DATAE84JSC6H85R_53: dc.b $3
	dc.b $F4, $D, $8, $0, $E4
	dc.b $FC, $5, $8, $8, $4
	dc.b $4, $8, $8, $C, $EC
DATAE84JSC6H85R_54: dc.b $3
	dc.b $F4, $D, $8, $0, $FC
	dc.b $FC, $0, $8, $8, $F4
	dc.b $4, $C, $8, $9, $F4
DATAE84JSC6H85R_55: dc.b $3
	dc.b $F0, $E, $0, $0, $EC
	dc.b $F8, $1, $0, $C, $C
	dc.b $8, $C, $0, $E, $F4
DATAE84JSC6H85R_56: dc.b $3
	dc.b $EB, $9, $0, $0, $F4
	dc.b $FB, $E, $0, $6, $EC
	dc.b $3, $1, $0, $12, $C
DATAE84JSC6H85R_57: dc.b $2
	dc.b $F0, $F, $0, $0, $EC
	dc.b $F8, $2, $0, $10, $C
	even